### ISSUE TITLE
surachi: delete ceramics entry

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1142]
I forgot to give it a delete button. 
I also must not forget to grant the normal user the rights to delete

**Comment by urapadmin** [comment]
### @test recording 10.7.1
there is a delete button now for everybody

**Comment by lbestock** [comment]
The button is not there for a normal user (I signed in as PVD himself).
Two things I am not sure if were intentional:
There is no warning on deleting it, as there usually is for deletion.
If all the fragment records are deleted there is still a ceramics processing record and so the bag itself cannot be deleted in CM.

**Comment by urapadmin** [comment]
### recording 12.11
- button there now for everybody always
- I cannot reproduce the second issue. In fact you can always delete a bulk even if there are actual fragments. So that sounds like confusing the fragment analysis with the ceramic preprocessing. Please have a second look at this.

**Comment by lbestock** [comment]
I am indeed confused because of terminology and thus expectations, so I will describe what I can and cannot do and see if it is what you intended.

- I can delete a bulk ceramics if it has basic information attached to it.
- I cannot delete a bulk ceramics if it has intermediate ceramics processing data in it. 
- I cannot delete a bulk ceramics if it has sherd processing in it. Both of these, I get a message saying it cannot be deleted because there is a ceramic record and a CM photo. This is the case whether I am logged in as just a registrar or an admin.
- I can delete an intermediate ceramics processing line with data in it.
- I cannot delete (there is not even a button that I see) a sherd in the sherd processing module, whether I am normal or admin.

**Comment by urapadmin** [comment]
For clarification: What you call intermediate ceramics I call ceramics preprocessing.
what you call sherd processing is what I call su ceramics or ceramics analysis. So there are a few issues here it seems:

- [ ] deleting bulk ceramics should be possible even if there is a fragment in su ceramic analysis (I don't see why one would do that but in the end the two things are not technically dependent upon each other)
- [ ] su ceramics should have a delete button visible to registrars

**Comment by urapadmin** [comment]
please don't forget the "back to developer" setting for the testing project or I am likely to miss the ticket

**Comment by urapadmin** [comment]
the sherd processing has a very red delete button:
![image](https://user-images.githubusercontent.com/38838314/168179933-2b109931-6735-48c2-a4ba-52aa85928135.png)

It is only visible if you select a sherd.

**Comment by urapadmin** [comment]
I have thought about it again, it is necessary to delete the fragments of a collected material that's deleted. So, new:
- [ ] if a collected material has at least one fragment in su ceramics (the one under "registrar" user's will be warned about it.
- [ ] deletion is nonetheless possible but the fragment data will be deleted, too. (That can be tested by creating a cm and a sherd for it, let's say a fragment LA-014C-001. Then delete the CM. And then create a CM under the same number, so LA-014C again. Go to su ceramics and try to create the same fragment CA-014C again. That should be possible.

**Comment by urapadmin** [comment]
apart from that I can't really reconstruct your issues

**Comment by lbestock** [comment]
I can delete a fragment now.
I still cannot delete a bulk ceramic-diag if it has either preprocessing or sherd processing or both associated with it.
![image](https://user-images.githubusercontent.com/49291909/168477473-f751838b-abc5-4660-b28a-b615d7f2badf.png)
![image](https://user-images.githubusercontent.com/49291909/168477358-820e47ee-8872-4ddc-bc00-b23f33597751.png)
![image](https://user-images.githubusercontent.com/49291909/168477409-032c0c57-0a31-401b-9401-6dbbc818c89a.png)

The thing is, this doesn't conform to what you say above but it is what I would have expected otherwise and wanted.

**Comment by urapadmin** [comment]
it is correct.
