### ISSUE TITLE
special finds problems for SU

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1146]
Special finds are going to be a headache for s'Urachi, but what drug to take to alleviate the headache is not yet clear to me. One problem is process: when do they define something as a special find? With ceramics it seems definitely after the fragment numbers are assigned, which means it's a function of the ceramics processing not the bulk collection. And this is going to be a problem for other types of special finds, too. For instance SU18D182 has two metal special finds. The way of making SU CM identifiers means you cannot have two entries for SU18D182E. But they are two objects, with two sets of measurements and separate photographs. They get separate lines in the D-reperti particolari tab of the SU excel file. They are aggregated as one line in the area D tab. One step is to ask Peter about the process of assigning special finds status to something, but I don't think that's going to solve the problem.

**Comment by urapadmin** [comment]
I think the solution here is clear. Small finds have to be N relations to the collected material instead of an 1 relation as we have in Uronarti. Uronarti is in fact the oddity here and I remember there was confusion when we designed that part in the beginning. 
So per collected material there can be N small find records each of which then would get its own identifier. That would be the small finds number. On what grounds that gets created is then a matter of their workflow. 

It would be interesting to hear how USTP handles it.

**Comment by urapadmin** [comment]
as it would in general be interesting to hear how close what we made for Peter is to something they could use

**Comment by urapadmin** [comment]
and here is the ticket to make it happen: #1489

**Comment by urapadmin** [comment]
we have discussed this in length and we have a solution documented under #1489
