### ISSUE TITLE
CM date for s'Urachi, USTP, and similarly constituted projects is a range

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1150]
For projects that collect materials by context, not giving new numbers to bags, the date field in collected material is problematic. A date range was requested by Peter. I asked if an opening and closing date would be good and he was enthusiastic and thought it would even be helpful for registration. I did not ask but we would want to know: should the CM just take the opening and closing dates of the whole context? Or is there any reason for it to be different? Please weigh in, projects that collect finds for a whole context instead of giving bag numbers!

**Comment by urapadmin** [comment]
My opinion is that by avoiding the false precision we add quite some complexity to the analysis stage (think about future queries which would differ between projects that use the cm date and those that use a locus range). 

We talk about "date" collected, right? I'll try not to question why it is important that this date is not more accurate than the range it is in. MY first instinct is not to blow up the data-structure unnecessarily. So I'd say make the date invisible in cm. The locus has an opening and closing date. 

BUT: The implication for the director's view (just the first thing that comes to mind) would be that collected material does not show up ever. Or the director's view would have to handle different types of projects on that front (which I will avoid at all costs)

So, the most straight forward way would be to make this an option for ALL projects. So all projects will have a date collected from and to (but if the locus is still open, who adds the "to"?). In that case I would change the director's view accordingly and it would work for all projects the same way. And future queries will have to take care of the range as well. This is work (and I hope this is not just nit-picky accountant-thinking. What problem do you anticipate if the date collected is inaccurately precise?),

**Comment by cmrice-arch** [comment]
We don't use closing dates. We include a tag with each bag of collected material and the tag includes the date and the context number. For our analysis, the context number is the important part. Once we wash, sort, weigh, etc., we don't generally keep things separated by date.

**Comment by urapadmin** [comment]
that sounds to me that you are fine with the single date per collected material, right?

**Comment by cmrice-arch** [comment]
I think so. Tyler? @Tfranconi ?

**Comment by urapadmin** [comment]
> 
> 
> We don't use closing dates. 
Does that mean you don't record when the locus is closed? I just ask that because of quality control. Your project would be different in that regard from others.

**Comment by cmrice-arch** [comment]
Yes. As is, we do not record when the locus is closed. Should we? Probably. But we have not in the past. Not on the formal context sheets at least.

**Comment by Tfranconi** [comment]
Yes Candace is right on this. We're fine with a single date, and all
ceramics from a context, regardless of day collected, are joined into a
single bag or crate or whatever once the context is finished.

---

Tyler Franconi
Visiting Assistant Professor of Archaeology
Joukowsky Institute for Archaeology & the Ancient World
Brown University
Box 1837, 60 George Street, Providence, RI  02912, USA
***@***.***

**Comment by aes1884** [comment]
My instinct is to say that S'Urachi is in a similar situation. If I remember correctly, there aren't dates on the bags/their tags, and even if there are, we also don't keep things separated by date once washed, etc. For further analysis and processing, the only date that really matters is the year, and that is already in the context number. So it seems to me that there wouldn't be much practical difference between a single date, a range, or no date, at least for the project. For a range though, the opening and closing of the context would be fine. It is entirely possible that I am missing something however, since I don't know the ins and outs of the whole recording process.

I also feel the same about College Hill. We collect by context and don't look at the date again, so the date more serves as date of record creation rather than telling us anything about the CM.

If there were no date, could it still show up in the director's view if a date is automatically assigned to the creation of the record? Could that be done behind the scenes?

**Comment by lbestock** [comment]
I am trying to think about when and to whom the specific date matters on collected material. The director's view is already in discussion - a director wants to know that stuff is being found in a context. The other is the registrar, and that is even more important. And for that, the closing date of the locus as a whole isn't really so relevant - the point is: when does stuff come back to the house/lab/campsite? As in, when does it move from being field stuff to being in the registration/photography/drawing/whatever each project does workflow? Both of those are precise dates, a date at which a bag of stuff is first opened (matters to the director who needs to know there is stuff in that context) and a closing date when the stuff comes to the lab (so the registrar is on it), right? They are not either one of them necessarily the opening and closing dates of the context itself. While the end date really is the only thing the registrar needs, the director will want to know in between if a context is still actively producing stuff that gets collected. But of these needs it really is the registrar's that is the more critical - if a bag of stuff comes back and the registrar doesn't know so then the chances of actually losing things are much higher.

**Comment by Tfranconi** [comment]
I agree with this. We date the pottery quantification sheets and that acts
as our marker of a context being completed and analyzed. All other finds
are dated in their respective spreadsheets as they are entered, mostly the
same day. So, I guess that for our purposes, it would be useful to have the
option to date the entry of finds into the database rather than necessarily
note when a context is closed. I suppose we're also a bit different in that
a director fills the registrar role, so there are fewer parties for these
data to pass through.

---

Tyler Franconi
Visiting Assistant Professor of Archaeology
Joukowsky Institute for Archaeology & the Ancient World
Brown University
Box 1837, 60 George Street, Providence, RI  02912, USA
***@***.***

**Comment by urapadmin** [comment]
@lbestock: Where are we with this? I tried to get a gist out of the discussion (as in is there something to do), but  failed.

**Comment by lbestock** [comment]
While the actual date of collection is a range, it seems no one records the date as a range. Either it isn't recorded at all, or it is recorded on analysis or inventory. The option to date the entry as opposed to the finds is already there - the Collected Material date can be used with the clock stamp but it doesn't have to be. The only confusing thing there is that it is labeled "date collected". 

So only one action item: add a configuration for label for CM date collected, so projects can make it instead "date recorded" or "date inventoried". And it can of course be left blank.

As to Anna's question, if it is left blank then it would still indeed show up in director's view on the day it was made. And it would show up again in the director's view on any day or days that the record was modified. So the director's view would (if used as intended during the process) catch both when it was created and when work was done on the material, and I really don't think adding more date stuff aside from label configuration does anything.

**Comment by urapadmin** [comment]
can we close this? Or is there something to do that came out of this?

**Comment by lbestock** [comment]
Nothing to do came out.
