### ISSUE TITLE
start screen: searching for identifier and navigating to it doesn't work

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1403]
This is just using the often overlooked search button on the start page, searching for an identifier and when clicking on it not getting anywhere.
I have tried MA-009 and MB-002. No locus opens.

"MB" on the other hand at least opens the unit MB.

**Comment by urapadmin** [comment]
### test: recording 12.1.0
- fixed and made the button a bit more sticky-out

**Comment by luizaogs** [comment]
This is working, but two questions/observations: 

1. Currently one needs to click on the identifier twice for it to go anywhere (once to close the keyboard, I guess, and another to actually click on it). Not sure if anything can be done about it, but noting it.

2. I guess this search is really meant for someone who knows they are looking for a specific locus (or feature, what have you). Right? I ask because I was going to ask if enabling autocomplete or something similar that would pull up several instances of "LA-" as I'm typing that out would be useful, but if the intent is just to enable a user to go straight to a very specific locus (etc.) that is not helpful.

(Sticky-out is a great word.)

**Comment by urapadmin** [comment]
1. seems to be an ipad speciality (I suppose you are on one, right?)
2. That is right. It is meant to take you straight to what you already know is there. However, you may open a new ticket if you think it useful to get a list of matching identifiers.

**Comment by luizaogs** [comment]
1. Yes. Lovely iPads.
2. I do think it is useful (particularly because it tells me that the identifier cannot be found until it is fully typed out), so: #1411

**Comment by urapadmin** [comment]
yup - no problem on FM for Desktop
Can't do anything about it on FM GO. Selecting the control and then interacting with it are two different steps there, it seems.
