### ISSUE TITLE
USTP: material code for bag number

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1520]
The issue: We cannot distinguish different bulk kinds by its mere number. But to apply photos via file import we must. So the idea is to use the same numbering system we invented for s'Urachi:

When creating a bulk material the first question is about the material. On the basis of the material a number is created that starts with the context's number and then adds a code depending on the selected material. So that the system knows what code a material to map to this list needs to be configured:

animal bone=B
ceramic=C
charcoal=O
clay=O
faience=H
human remains=human
glass=H
ivory=O
leather=H
metal=M
organic=O
paper=H
papyrus=H
shell=O
stone=S
textile=H
wood=O

The B,C,O etc. are the codes that will be added to the context#.

So adding bones to context 1234 would lead to the bulk number 1234B
(we could also make it a 1234-B).

Now some trained archaeologist has to decide on the codes and the mapping. The list above is an example (but based on the current USTP material list).

Just tell me your list and I will configure it.

**Comment by urapadmin** [comment]
It's cool. I really begin to like our numbering system. No matter how crazy my archaeologists get, I'll create their identifier as long as there is any sense in it.

**Comment by lbestock** [comment]
You only begin to like it now? 
Your archaeologists are kinda crazy.
This one has a question. Your above list to my example-bound mind is nuts. If clay and organic and shell are all O then there is not anything unique about those identifiers. And what is up with "human" where everything else is a single letter? I can be decisive and make codes, but I need to know within which bounds.

**Comment by urapadmin** [comment]
the above list is there to give you an example HOW IT WORKS and not what material codes to use. It is entirely up to you what code you set for what material. You can set them all to Blubb (yes, it does not have to be a single letter) or what not. 
It depends on how USTP organize their finds. I am sure they don't have separate bags for every single material. But for every bag type there should be a code. That's the idea.

**Comment by lbestock** [comment]
We will use a combination of single letters and dual letters where needed. I agree with you we should make short numbers.

I will not ask what they write on the bag; we already know there is no unique ID and that uniqueness comes from the combination of context and material. This below makes sense and they will have to tell us if they reject it and why, but I don't think they will.  

animal bone=B
ceramic=C
charcoal=CH
clay=CL
faience=F
human remains=HR
glass=G
ivory=V
leather=L
metal=M
organic=OR
other=OT
paper=PR
papyrus=PP
plaster=PL
shell=SH
stone=S
textile=T
wood=W

**Comment by urapadmin** [comment]
Does that make sense? They bag these things differently? I have my doubts.

**Comment by lbestock** [comment]
I am not sure what you mean by differently? They have a bone bag, which gets labeled 1234. And they have a metal bag that gets labeled 1234. The tag also says bone, or metal, but that is not part of the number. Tags usually have other information, too, such as the date and excavator. But here we're only talking about the number. We would now be asking that they write 1234-B as the number, and continue to add whatever other information (presumably spelling out bone still) they want on the tag.

Though I now remember that they also have 45 bags of plaster that each get labeled 1234, no distinction, which is why we allowed for non-unique USTP numbers in the first place. Does it work to make them still non-unique, but distinguishable as CM numbers from the locus numbers?

**Comment by lbestock** [comment]
It would be more convenient for them on the tag, but in the recording system it would look ridiculous. The number then would be 1234 human remains. And so the line in the CM would look like 1234 human remains human remains :)

Which is why you would cut it down. 

This would then LOOK like what we gave them initially: 1234 (bone). And so I can't imagine it would cause any upsets.

**Comment by urapadmin** [comment]
I have configured USTP accordingly. You may look at it.

**Comment by urapadmin** [comment]
### recording 12.5.2/USTP 08.IV.2022

**Comment by lbestock** [comment]
First notes on testing USTP configuration. I have not tried to change anything in here, but am noting all the ways where it did not behave how I expected it to.

Why is a carrot better than a delta?

But more pertinently:
A ^ is added all over the place where as it should just be added to Small Finds.
It is added to a new trench ID.
It is added to a new context ID.
It is added to CM bulk.

In the case of making a new context, the ID was pre-filled and I had to erase it. It was pre-filled with the trench ID.

The same was true of making a Small Finds record - pre-populated with the trench ID, though I could change it.

I was unable to make two bulk records of the same material.

The Filter by Type does not work in the CM list (perhaps because the "insert" popup is over the place I need to type so I can't even see if I am typing anything, but also that should be a drop-down menu if possible, since bulk, small find, and sample are set).

Samples do not show up as CM in the Director's View. (Bulk and Small Finds do.)

It would be really helpful if one could see the last used number (I suspect that's not a small ask) for the current way of assigning small finds numbers. It was fine for me - I only made a small handful and remembered where I was. But if there were hours or days involved here one would be totally lost about what to call one's next number. Even sorting by small find in registration (which would not be possible for an excavator, and that number gets assigned in the field while the surveyor is right there) doesn't work. If one has put a type in for the SF then it takes that into account and sorts by SF types, so the list ceases to be numerical.

On doing an import of photos I did not get asked about the lots/tons, but it was set at lots and only let me do 10 at a time. I'm not sure if that's just because I'm on an online server and tons wouldn't be an option anyway?

The QR code workflow for small finds photography was surprisingly smooth - way better than anything I've ever actually used in the field, and this was my first time trying to do it for multiple objects in the same session.

**Comment by urapadmin** [comment]
> Why is a carrot better than a delta?

I don't have a delta on my keyboard. The delta would be part of the number! So searching in the file repository or whereever requires it being typed. Am I happy with it? No.

**Comment by urapadmin** [comment]
> On doing an import of photos I did not get asked about the lots/tons, but it was set at lots and only let me do 10 at a time. I'm not sure if that's just because I'm on an online server and tons wouldn't be an option anyway?

that's exactly the case.

**Comment by urapadmin** [comment]
> ... but also that should be a drop-down menu if possible, since bulk, small find, and sample are set).
No, a dropdown does not work here because once it is a small find, the small find type is also part of the type displayed here and can be filtered as well. cm type and small find type can't share a list. But even with only cm: Peter has ceramic-diag and ceramic-non-diag or so and the text filter allows to filter by "ceramic" and get both types

**Comment by urapadmin** [comment]
> It would be really helpful if one could see the last used number (I suspect that's not a small ask) for the current way of assigning small finds numbers. It was fine for me - I only made a small handful and remembered where I was. But if there were hours or days involved here one would be totally lost about what to call one's next number. Even sorting by small find in registration (which would not be possible for an excavator, and that number gets assigned in the field while the surveyor is right there) doesn't work. If one has put a type in for the SF then it takes that into account and sorts by SF types, so the list ceases to be numerical.

That would be possible somehow for the local device. Only misleading since one does not know about other devices in other units. They have to do it as always: Keep a running list outside of the recording. In that case seeing the last small find number is not necessary.

I am very surprised, though, to find free input for locus creation here. How does that work in the field?

**Comment by urapadmin** [comment]
> I was unable to make two bulk records of the same material.

that should not be necessary any longer now that the material is actually part of the identifier. Why would one make several bags of ceramics if they are in fact all one bag (not distinguishable at all)?

**Comment by urapadmin** [comment]
> In the case of making a new context, the ID was pre-filled and I had to erase it. It was pre-filled with the trench ID.
> 
> The same was true of making a Small Finds record - pre-populated with the trench ID, though I could change it.

should be okay now

**Comment by urapadmin** [comment]
> A ^ is added all over the place where as it should just be added to Small Finds.
> It is added to a new trench ID.
> It is added to a new context ID.
> It is added to CM bulk.

should be okay now

**Comment by lbestock** [comment]
> 

Hmpf this tripped me up again. The "insert" menu still flies around uselessly, though it no longer prevents me from typing. But I tried to filter by small finds and it really took me four tries to get it. First I capitalized it. Then I hit return for enter, which not only doesn't enter, it gives another line which then screws up the search. Then I said small finds, but it is small find.

**Comment by lbestock** [comment]
Some other notes, partial. Mostly this is all taken care of and working smoothly.

Is it possible to remove the + button in the CM by trench? It is inert, but it would be less confusing to have it gone.

When one is in a CM record there is no way to distinguish a bulk record from a sample. I was interrupted in the middle of making a record, which is not uncommon in the field, and on returning I didn't know what I was doing and could not tell from looking if I had made a sample or a bulk. We should make that clear. 

Faience and Sample both have code OT, which is the code for other. So once a faience bulk is made, for instance, a bulk "other" cannot be made. Two things there. One is just that the code is wrong (and in the popup where one creates it, Faience is said to have code F but then it applies code OT. Sample says it has OT and applies OT. Other has (and should have) OT and applies OT.) But the second thing there is that at least other does indeed need to be able to have multiple bulks made. Because there could be different others.

**Comment by lbestock** [comment]
Thinking more about the filter. This is not analysis. What do I want that filter for in the CM tab of a locus? We never thought of it until we had the tripartite CM structure. Two things I think I want to find are whether or not I have already applied a material in bulk, and how many small finds there were from a locus. Oh and in a locus dug for days, did I already get soil samples? I really did not expect and cannot easily imagine wanting (here) a filter that is more than bulk/small find/sample.

**Comment by urapadmin** [comment]
> > > ... but also that should be a drop-down menu if possible, since bulk, small find, and sample are set).
> > 
> > 
> > No, a dropdown does not work here because once it is a small find, the small find type is also part of the type displayed here and can be filtered as well. cm type and small find type can't share a list. But even with only cm: Peter has ceramic-diag and ceramic-non-diag or so and the text filter allows to filter by "ceramic" and get both types
> 
> Hmpf this tripped me up again. The "insert" menu still flies around uselessly, though it no longer prevents me from typing. But I tried to filter by small finds and it really took me four tries to get it. First I capitalized it. Then I hit return for enter, which not only doesn't enter, it gives another line which then screws up the search. Then I said small finds, but it is small find.

You are not using it the way it is meant to be used. No reason to type in small finds. type "find" or "small" or what not. Much quicker. 
- [ ] I will make sure that capitalization makes not difference (I do recommend to switch off the really not smart capitalization feature of the iPad, though. I always think it does as much harm as it helps)
- [ ] I can do something about the ENTER because that is also annoying on PCs (see below)

I really don't see a reason to limit functionality artificially to what you can imagine right now (right now that you are also annoyed with how it works). Since we don't have any other way for analysis this is a simple but powerful feature if used correctly. I wanted to extend the cm type/material field in fact so that it contains a detail for bulk and samples as well. Bulk and samples just don't have any details, yet. Perhaps we could get rid of the "material" column entirely and use that instead.

**Comment by urapadmin** [comment]
> Thinking more about the filter. This is not analysis. What do I want that filter for in the CM tab of a locus? We never thought of it until we had the tripartite CM structure. Two things I think I want to find are whether or not I have already applied a material in bulk, and how many small finds there were from a locus. Oh and in a locus dug for days, did I already get soil samples? I really did not expect and cannot easily imagine wanting (here) a filter that is more than bulk/small find/sample.

yes, this is analysis. It is not a feature you need in the trench. It is analysis only and you count your beads and arrow heads here, either on locus or on unit level. And if you are clever you don't use an ipad for it (much harder to use) but a computer. Then most of the handling issues go away. I maintain that if that's all you want to find then great, you got it. Other's might want to find different things and they can do it to.

**Comment by urapadmin** [comment]
Also, this is getting a nightmare to work with. Can you please make single issues single tickets?

**Comment by urapadmin** [comment]
> Faience and Sample both have code OT, which is the code for other
- [ ] This is a USTP only issue and just a matter of configuration. Faience should have code F.

**Comment by urapadmin** [comment]
> Some other notes, partial. Mostly this is all taken care of and working smoothly.
> 
> Is it possible to remove the + button in the CM by trench? It is inert, but it would be less confusing to have it gone.
> 
> When one is in a CM record there is no way to distinguish a bulk record from a sample. I was interrupted in the middle of making a record, which is not uncommon in the field, and on returning I didn't know what I was doing and could not tell from looking if I had made a sample or a bulk. We should make that clear.
> 
> Faience and Sample both have code OT, which is the code for other. So once a faience bulk is made, for instance, a bulk "other" cannot be made. Two things there. One is just that the code is wrong (and in the popup where one creates it, Faience is said to have code F but then it applies code OT. Sample says it has OT and applies OT. Other has (and should have) OT and applies OT.) But the second thing there is that at least other does indeed need to be able to have multiple bulks made. Because there could be different others.

The question is always: Are they bagged differently? If OTs are bagged differently. How are they OTs anylonger? If there is a critieria as to how to bag them separately, I would use that criteria for differnt codes. I really think this is pretty hypothetical.
The very moment we allow for non-unique bag numbers the file import can't apply images anymore. And the bags will be indistinguishable anyhow. If it is 15 bags of plaster. It can still be one record in the collected material. The only information you might lose is how many bags they actually were. That could be a note in the description. At least Peter explicitly said that he does not make a difference between bags it is just one huge pile of material. 

(User's manual: "how do I add a new material?" If people come up with a new material, they need to know how to apply a new material code as well.)

**Comment by urapadmin** [comment]
can we close this?

**Comment by lbestock** [comment]
Yes.
