### ISSUE TITLE
director's view: samples not showing up

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1535]
_Originally posted by @lbestock in https://github.com/arch-kiosk/arch-kiosk-office/issues/1520#issuecomment-1094132006_

**Comment by luizaogs** [comment]
I was going to open a ticket for CM in director's view but found this and figured I would just add to it. The issue seems a bit more complicated than just no samples showing up? The label for the widget is "bulk," which confused me at first because I was looking for CM. Once I realized that widget contained all of the CM types I saw that I can filter by small find, but I wonder if it would make more sense to have an overall CM widget (rather than call it bulk) in which one can sort by all three types? 

<img width="832" alt="Screen Shot 2022-04-21 at 12 01 33 PM" src="https://user-images.githubusercontent.com/67970402/164513289-ddf77ddb-1060-4d25-88cd-db45f9088ac7.png">

**Comment by luizaogs** [comment]
Oh also, I just tried sorting by small find and that didn't work.

**Comment by urapadmin** [comment]
I have not attended to the director's view, yet. It needs quite some change now that we have collected material types

**Comment by urapadmin** [comment]
### kiosk 0.18.4
- director's view shows the collected material type now instead of a "small find" checkmark

**Comment by urapadmin** [comment]
doesn't work Shows "bulk" all the time.

**Comment by urapadmin** [comment]
ja, it really didn't work. It so didn't work.
### kiosk 0.18.5
- Now totally different approach. That should work.

**Comment by luizaogs** [comment]
Works!
