### ISSUE TITLE
unit creation warnings show up twice

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1573]
Came out of testing #1572. 

If I get a warning when creating a unit (doesn't matter if it's for a lack of a unit identifier, for a lack of a term for context, or for a lack of a term of unit) it shows up twice. I click on "oh, ok" and the warning comes back, and only when I click on "oh, ok" again can I move on.

**Comment by urapadmin** [comment]
a pity :o)

**Comment by luizaogs** [comment]
yours truly strikes again

**Comment by urapadmin** [comment]
### recording 12.10
It is for you only. Because I usually don't touch this dialog. It is so screwed that I am always afraid to produce side effects (and I just did). So yours truly needs to test this horror dialog now again. One gets in there by editing an existing unit and by creating a new one AND through the gear button in the first tab of the excavation / survey / feature layouts.

**Comment by luizaogs** [comment]
You know that you can (and probably should) ignore me sometimes, yes?

**Comment by luizaogs** [comment]
Ok, it is working for both editing and creating a new unit. But am I blind? I do not see gear buttons on the first tab of any unit type.

**Comment by urapadmin** [comment]
ha. I am on full excavation. It is a full excavation relict. And I think we should forget it.

**Comment by luizaogs** [comment]
Oh ha yes, I thought you had gotten rid of that. Well, good.
