### ISSUE TITLE
non-diag not showing up in ceramics module immediately

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1579]
I don't know if this is actually a problem or if it is a side effect of some ceramics configuration that I do not understand, but I just noticed that if I create a non-diag bulk and then try to start recording sherds for it in the Ceramics tab under registrar it does not show up automatically: 

<img width="1027" alt="Screen Shot 2022-04-21 at 11 34 28 AM" src="https://user-images.githubusercontent.com/67970402/164508480-6730c234-fa83-40ec-a36e-86095ff27a02.png">

If I then type in "non-diag" it shows up in the search: 

<img width="1028" alt="Screen Shot 2022-04-21 at 11 34 52 AM" src="https://user-images.githubusercontent.com/67970402/164508502-6887dbbb-8b55-4d37-b8a1-24fb6400dfd7.png">

And then if I backspace it appears in the list: 

<img width="1024" alt="Screen Shot 2022-04-21 at 11 35 33 AM" src="https://user-images.githubusercontent.com/67970402/164508636-a721e470-174f-4df5-86b7-124ec1121b8c.png">

Once I find it I am able to start processing it, so it seems like the issue (if there is one) is it not showing up in the list for some reason.

**Comment by urapadmin** [comment]
you should only see ceramic-diag bulk in this list.

**Comment by urapadmin** [comment]
why you can see the sample in the first place is beyond me. I have to look into that. It looks like a bug.

**Comment by urapadmin** [comment]
okay, several things here:
1. config key "visibility/show_only_this_material_in_pottery_selection" determines which collected materials show up in the selection. It looked strange to me because a sample should not show up here. But then there should not be a sample with material type "A-DIAG" which I suspect is the case with your SU22-C200-sample?
2. Only ceramic-diag should show up here.
3. your filter issue is the real bug here. And such an oooold one. Funny. That code is from 2015.

### recording 12.10
- the selection should always only show collected materials of the material type that is set in "visibility/show_only_this_material_in_pottery_selection" no matter if there is an additional search term entered or not

**Comment by luizaogs** [comment]
Yes, when I was trying to get the preprocessing tab I added diags everywhere :) Upsala.

**Comment by luizaogs** [comment]
It looks good now.
