### ISSUE TITLE
site name cut off in display

### ISSUE THREAD

**Issue by aes1884** [arch-kiosk/arch-kiosk-office#1584]
This is very minor, but in the area level of the database, the site name only shows 'Nuraghe' and not the 'S'Urachi part'
<img width="772" alt="image" src="https://user-images.githubusercontent.com/68443221/164554132-7d568ac3-66fa-43c1-b664-e2598f7ed52b.png">

**Comment by urapadmin** [comment]
again, this looks like Windows. see #1585 
Please report your screen scaling and your windows version and try if that changes things.

### recording 12.10
- since in this layout I can find the space I have extended the white space that holds site and trench AND I have reduced the font size of Site.

**Comment by luizaogs** [comment]
This had also been the case for me in the previous version but it hadn't registered as an issue before Anna pointed it out. It now looks good on both my Mac and my iPad.

(Survey and feature layouts both have the site name cut off too, but since PASU isn't using those I am not opening a ticket for that.)
