### ISSUE TITLE
PASU file picking question / potential heic issue?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1588]
I forgot to open this ticket yesterday, but I realized that one of my images didn't come back to FM after synchronization. In FM I get the typical "this file has been omitted" message that usually results from file picking as far as I am aware, but there are no file picking rules configured for PASU other than low for contextuals so I am not sure why I would have a dummy. It is an HEIC so that might be the issue, but #17 makes me think that has been resolved? So not sure. 

It's image 9aa8ca2f-978d-466d-9f63-1b855737ece6.

<img width="1025" alt="Screen Shot 2022-04-22 at 8 27 57 AM" src="https://user-images.githubusercontent.com/67970402/164723753-afa075af-7192-4b75-ba54-d543d0b4aa18.png">

**Comment by urapadmin** [comment]
Indeed:
"FileMakerWorkstation._prepare_file_for_export_v2file: file 9aa8ca2f-978d-466d-9f63-1b855737ece6.heic not prepared for workstation because file extension is not supported by file handling."
That's just missing in the config. But should not by default, so it is also an issue for the default configuration shipped with kiosk.

**Comment by urapadmin** [comment]
- changed in all project on Beset
- hence works now in PASU and PVD
- added to the base configuration
