### ISSUE TITLE
where: new locus error

### ISSUE THREAD

**Issue by nparkervan** [arch-kiosk/arch-kiosk-office#1642]
(please remove instructions and sections that don't apply)
please give a title that indicates where you encountered the bug (e.g. file repository, locus layout) followed by a colon and a short descriptive/summarizing title.

**if this is a bug, describe the bug**
- What did you expect and 
- what happened instead?

**To Reproduce**
Steps to reproduce the behavior if it seems a tricky one (you may delete this if no particular steps are needed and the thing is a clear case)

**Screenshots**

**where exactly did it happen**
- Please choose a label: Either "filemaker" or "kiosk" to indicate where the bug appeared. 
- give a hint here in which part of the software it happened. E.g. "file repository" or "administration" or "locus layout" or so.

### prerequisistes
if this issue depends on other issues that should be tracked, add the task list here or delete this section
- [ ] e.g. task 1
- [ ] e.g. task 2

**Comment by nparkervan** [comment]
![AAB2A8D8-1DD1-4614-91D3-72028AEC5D4F](https://user-images.githubusercontent.com/7636871/168479696-9b9bfdfa-0e90-4846-ba7d-7ddc73bf114d.png)

**Comment by lbestock** [comment]
Yup, you need to assign a range of locus numbers to this unit since your locus numbers don't include your unit number.

- From the start page, choose the tab registrar and specialists.
- On the left side, choose the button identifier lists.
- Once there, at the top in "identifier list" choose locus_numbers.

It should look like this:
![image](https://user-images.githubusercontent.com/49291909/168480033-1500bf9a-95e6-466b-b6b1-2a123bd2990a.png)
Those are all the units (partitions) with the range of locus numbers assigned to them.

- Click the + button to make a new one. Since locus numbers 1-649 are taken, define a range starting with 650. Make the partition match the unit name you want, in this case Test01.
- Should all work!

This seems cumbersome in a test scenario but you can set them before the units are defined. So if you know you'll have 6 units, name them and define their locus number ranges all at once and you'll be good to go.

**Comment by urapadmin** [comment]
can we close this?

**Comment by nparkervan** [comment]
Yes thanks!
