### ISSUE TITLE
workstation import: how to override file import issue

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1663]
Parker had that issue: downloaded a workstation, presumably worked in an older one, at least in a different one, and tried to upload that one instead of the one that was downloaded last. 

That's the end of that workstation. No way back and the new data of that day would be lost. So how could one override the safety catch and what would the consequences be? 

- switch off deletion for both import and synchronization?
- there is still the #48 ticket from aaaages ago that I was surprised to see implemented already. Perhaps we can use that in addition to something on the workstation's import side.

**Comment by urapadmin** [comment]
okay, this is how I plan this:
these issues could be overridden:
  - the whole "_prepare_import_from_filemaker" step could be omitted. It more or less just deletes empty dayplans. Make a config key to permanently skip it and allow it for a single workstation.
  - Importing the wrong workstation (different export_device_id) should not be skippable
  - Importing a workstation with the wrong fork_time should be surmountable per workstation BUT it should always deactivate the deletion of records: simply skip the sql statement that sets "repl_deleted" to True

**Comment by urapadmin** [comment]
### kiosk 0.25
  - if the import runs into one of these three issues, they can be skipped: 
    - the uploaded database does not seem to have ever been opened, 
    - the timestamp of the uploaded database does not match the timestamp of the downloaded database
    - something went wrong in a preparatory step (you can't test this)
  - in these cases the import has to fail first
  - if the user has the "manage server" privilege (or is an admin in general, which includes all privileges) the workstation should reveal a new button "import troublesome recording data" under "more options". 
  - if that button is been pressed, you should be asked if you know what you are doing
  - if you confirm with yes, the import should run and ignore the errors stated above (only those).
  - in this "repair mode" no records will be deleted. So if you deleted something in the database you are uploading you will only get a warning in the log that there are records that should have been deleted but they are not deleted.
  - other issues, e.g. uploading a database from a different workstation, cannot be skipped using the repair mode.

**Comment by lbestock** [comment]
First test of the normal case had an unexpected situation, so something in normal synchronization is up.

I prepped all workstations in PVD.
I downloaded my Mac.
I added a narrative.
I uploaded and imported and ran synchronization.

![image](https://user-images.githubusercontent.com/49291909/170841080-480b2368-9900-4084-b893-f9df3da8933f.png)

However, when I click the back arrow the Hubbub tells me my dock is synchronized and ready to prepare, and Director's view tells me my change has been synchronized properly.

**Comment by lbestock** [comment]
Unopened file works as expected through rejection and overriding the rejection for import. I did NOT get the unexpected transmission error after synchronizing (there would have been no changes in this case, if that is behind it.)

**Comment by urapadmin** [comment]
I think that's unrelated and just a hiccup. I have had transmission errors, too, in the past around synchronization. They don't do anything. If you go back the Hub should tell you that synchronization was successful and if you click on it you should see the log. 
Was that the case?

**Comment by lbestock** [comment]
Now the trial of one from the wrong time. I appreciate that the errors and the warnings are clear and are the same as one another. 

This seems entirely right, too. I get the error, then the warning. I had deleted a photo; that deletion was rejected (I did not understand the error message at synchronization on that front and thought I might have added a duplicate photo, but it seems not when I go into the File Repository). I had run synchronization with the defaults, so I didn't tell it not to allow deletion. It rejected deletion because of the new thing.

Batch import works as expected, allowing the good file and rejecting the wrong one. After synchronizing (not necessary, just a best practice workflow we discussed, and I note that it did not return the weird thing above and so I wonder if that was a hiccup) I am able to import my troublesome data.

Absolutely everything is as I expect it. My legitimate deletions in the right files are deleted. My deletions are not accepted in the wrong files, but all my added data are accepted. I get the warnings and steps I expect. 

I think this is really cool and solves one of our major problems. I also think it is working properly with the exception of that weird message I got after synchronizing when things were normal.

**Comment by lbestock** [comment]
I didn't try the log, I just know it was successful because it succeeded in getting my data in. I'll repeat my steps but was already suspecting a hiccup. In which case, huge as it is, can this really already be closed??

**Comment by lbestock** [comment]
This time I didn't get it. Looks good to me.

**Comment by lbestock** [comment]
Working as expected on Beset. Leave open until tested on a local server.

**Comment by lbestock** [comment]
Tested on PACHA. Slow like molasses but also does what it should.
