### ISSUE TITLE
file picking: dummies not shown in filemaker in various containers

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1692]
#1690 revealed holes in the way I obey file picking rules in filemaker. We need to look at every single container. The pop-up version should either be inaccessible for a dummy image or it should show a dummy image as well.

(Just use the "all" -> "dummy" rule to make you life easier)

- make sure that the dummy image shows up if file picking wants it
- make sure that the dummy image does not show up but instead the image container if the image should show

**Comment by luizaogs** [comment]
Ok maybe I am again forgetting stuff here but shouldn't this have worked, since it is the lowest order rule? My logs told me it didn't work: 

<img width="1493" alt="Screen Shot 2022-05-26 at 2 32 45 PM" src="https://user-images.githubusercontent.com/67970402/170553710-69b8f84a-ec17-4a66-8a6a-ea172f86e025.png">

<img width="1503" alt="Screen Shot 2022-05-26 at 2 33 45 PM" src="https://user-images.githubusercontent.com/67970402/170553731-c3414afa-4dfe-46d3-a7d6-27fcd1c0fe4f.png">

**Comment by urapadmin** [comment]
That is the rule you would not need because it is the default, anyhow.

However, it would have worked if developers didn't have this strange 
habit of starting to count with 0. So the lowest order would need a 0.

Am 26.05.2022 um 14:34 schrieb luizaogs - ***@***.***:

**Comment by luizaogs** [comment]
Besides warecode pottery this is all good, so not sure if you want it closed or not.

**Comment by luizaogs** [comment]
(By which I mean, I haven't tested warecode pottery, not that it isn't good.)

**Comment by lbestock** [comment]
Warecode pottery is good! Closed as complete.
