### ISSUE TITLE
cannot delete photo in collected material photo

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1698]
not sure why, but there is no way to delete this photo here:
![image](https://user-images.githubusercontent.com/38838314/170791267-12811823-80ba-42ef-b45d-23549d15e402.png)

Might be a file picking issue? This is some old template I use for testing, so this might be fixed with #1692

**Comment by urapadmin** [comment]
I suspect it had to do with my test environment: @lbestock , can you please make sure this isn't an issue in the real recording?

**Comment by urapadmin** [comment]
I am rather sure that this was an image that was turned dummy by a file picking rule. So make sure that that's the case in your test, too.

**Comment by lbestock** [comment]
Hmpf I just deleted it when it was not a dummy because CA was set to low in my file picking. You think it is about this image particularly or dummy images? I am not able to delete dummy images in CM. But they also don't look like your screen above - they have dummy jpg markers, not the insert image thing you have there.

![image](https://user-images.githubusercontent.com/49291909/170843096-854e5d17-34b0-4e73-a409-35f7cc366264.png)

**Comment by urapadmin** [comment]
which is what should be the case. But you can delete images in cm that are not dummies, yes?

**Comment by lbestock** [comment]
Correct.

**Comment by urapadmin** [comment]
just my development environment then.
