### ISSUE TITLE
Turn search pop-over into a popup window and offer it everywhere

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1708]
when navigating the recording via the search function I always have to go back to the start page to click on the magnifying glass.
If I turn the pop-over on the start page into its own dialog (a pop-up dialog) I could trigger it from everywhere and make it a permanent icon in the menu.

**Comment by urapadmin** [comment]
### recording 13.14
- this is available now as an experimental feature in the burger menu of the locus layout

**Comment by lbestock** [comment]
No, it still does not work with scrolling on the iPad. (It also really doesn't work in portrait mode, but that's expected.)

**Comment by urapadmin** [comment]
### recording 13.5
- available now in collected material and excavating
- jumping back to the original layout where the search was done should be more coherent now

**Comment by luizaogs** [comment]
Ok so I am not sure if you only mean CM in locus recording units or not, so I note the following: the search button shows up in the hamburger menu of CM in locus recording as well as in excavating, as expected based on your comment above. It also shows up in features and in the CM for features, which you don't mention above. But it does not show up in survey at all, which I gather was not intended at this point but since it showed up in features I thought I would mention it.

**Comment by luizaogs** [comment]
An observation that I am not sure if you will want to address so I do not yet make it a new ticket, but can do so if desired: if I search for something and go to that record, the hamburger menu does not disappear once I arrive in that layout. I assumed it would disappear automatically and that I could then click on it again if I needed it.

**Comment by luizaogs** [comment]
If those two above things are fine as is, then this can be closed I believe (the scrolling still does not work, though).

**Comment by urapadmin** [comment]
### recording 13.6.13
- the pop-over that contains the search button should close automatically now

**Comment by luizaogs** [comment]
Yep.
