### ISSUE TITLE
file repository: date not shown in thumbnails unless sorted by date

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1711]
Images with dates do not display them in the thumbnails as I expected them to:
![image](https://user-images.githubusercontent.com/49291909/175781206-6c89d86f-4be3-491c-830f-71ac816e1449.png)

I noticed this after an import where I was careful to get the date from exif data, but then I saw that the date did not display on any images in PASU test, whether they have them or not.

I thought that was weird, but then I did a sort by date and then the dates show up. So this ceases to be a bug and is instead a question: should dates be visible always? When one sorts by context in the file repository, how are things sorted within contexts, then? It doesn't seem chronological?

**Comment by urapadmin** [comment]
it should be chronological within one context BUT oldest first. Did you expect it otherwise?
If dates should be visible always is a question I have answered by making it the way it is and I do note that it only comes up now that you test something about dates. The idea was to leave as much room for images and make the information more palpable on the screen. Too much information that you mostly don't need in the list is distracting. That is at least the rationale behind the current UI.

**Comment by lbestock** [comment]
I didn't expect it otherwise - that was what I expected (on the sorting within a context). Only I found that it holds true for all images except locus relation images, but even there I don't really think this is a problem. Short discussion. I think it is all fine.
