### ISSUE TITLE
PACHA: New field "datum"

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1740]
PACHA requests a float field "datum" in in the measurements where they want to record "the absolute value", "in meters above sea level".

`This will allow the recorders to indicate the precise height in m.a.s.l. of the datum from which they are measuring. `

**Comment by urapadmin** [comment]
@lbestock: need you here on the question where exactly to put it and if it makes sense as a general field for us. And meters as a float here and the rest in mm?

**Comment by lbestock** [comment]
Ah, don't kill me on this one. We should go to m not mm for the measurements in general. I have looked at a few formal reports from different places and elevations in all of them were reported in masl. (I also record them, when I record them at all, this way. I don't remember why we decided mm?)

The field does make sense as a general. This is back to the how one gets elevations thing we have discussed with the possibility of an automatic subtraction. There are two standard workflows to do elevations and how to accommodate both in the same layout is the problem - are the fields we have for the final actual asl measurement, or are they for the observation made in the field? Because sometimes the latter is the asl (if taken with an RTK, for instance). But sometimes the latter is a measuring tape down number to be subtracted from the datum. If the latter is the workflow (which it clearly is for PACHA and that is common - most excavations I've been on do this) then there is a conundrum. If those fields are final asl, there is nowhere to record the actual measurement taken in the field. I know from experience that doing the math at the time is unlikely. And our whole point is to give space for observations made in the field.

I mean, the real way to do it is messy for layout and complex for you. It would be a checkbox "are you measuring elevations off a fixed datum?" And then if that is checked, you see new field**S**. One is for the datum itself. And then you get a replication of all the elevations fields. The current elevations section, which everyone would have, would need a title like "elevations above sea level". And the new section, only present if you click the button, would need a title like "measurements from datum". We would then make it so the "elevatiosn above sea level" fields are not fillable if you have checked that box, but rather receive the value of datum minus measurement from datum. (Positive values are extremely rare but not unheard of with architecture so wow, that would need thinking, too.)

There is room for that on the layout if we make the width, lenght, etc how horizontally instead of stacked. But it's a lot to do in the midst of a season in particular, and one where you've just gotten Parker to start recording in mm already. 

For the time being we could just add the datum field. I would separate it by another horizontal line on the measurements tab, in between the two sections that exist so that it is visually prominent.

**Comment by urapadmin** [comment]
it is pretty easy to calculate meters from millimeters. Integers are very precise. It is harder the other way around. Integers also do not have an international problem (comma vs. point). That's why I am never sad to use an integer. But, who am I to battle good old archaeological customs. I'll ask Parker if he prefers to switch. Since I am on it, I can do that, too.

The name of that field cannot be "datum". That is not a name of a field. You both duck that question. What should I call it?

**Comment by lbestock** [comment]
The problem is that that is what one calls it in the field. "Datum Point Elevation" is unwieldy but accurate.

**Comment by urapadmin** [comment]
I will at least call it that in the database and then make the label configurable. I can't have a database field "datum". That is not a name specifying anything.

**Comment by urapadmin** [comment]
### recording 13.3
  - new field for datum point elevation on the measurements tab
  - only visible (including its horizontal bar) if key show_datum_point_elevation is "yup"
  - the label of that field is configured by key "label_datum_point_elevation"
  - the field accepts floating point numbers but it must be numeric

**Comment by lbestock** [comment]
All synchronizes and everything.
