### ISSUE TITLE
Map - narrative view in dayplans

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1776]
Idea coming out of #1775 : 

For dayplans I was thinking of a map - narrative view that can be activated in the narrative: It shows the current SVG (this time in a web-viewer) and the current narrative more or less full screen. The narrative would be editable. That would allow a good map - narrative interaction:

**Comment by urapadmin** [comment]
@lbestock: We need to talk about whether that would make sense and in what way it would make sense.

**Comment by lbestock** [comment]
Would it have to be just SVG? I am thinking one gets the SVG from the surveyor but for the next three days one's dayplan might be that base SVG modified as an image.

I can imagine this as very useful. I forget my locus numbers all the time while I am writing a narrative, and being able to look at the plan so that the numbers are legible while writing would help. 

It relates back a bit though to the issue of linking narratives and images. My first question, for instance, is how one chooses the image and narrative to show beside one another. "Current" isn't all that helpful because it can't be guaranteed (and shouldn't) that the workflow would lead to the two related things both being on top.

**Comment by urapadmin** [comment]
### recording 14.9
- the new layout is implemented in a first version: You find a new button next to each narrative (but only if you have entered at a date for the narrative)
- the layout starts with the tab with the calendar-icon: That means you see all images of the unit from the same day of the narrative. 
- you can associate an image with the narrative by clicking on the chain button
- the associated images appear in the image tab with the chain
- once there is at least on associated image for a narrative the layout will start with the list of associated images activated (instead of the calendar tab)
- the very left tab shows all thumbnails of all units
- you cannot add or modify the images in any way. This is only to work on the narrative while looking at the image
- If you have an SVG in the list, it will show as a green SVG thumbnail. If you click on it the SVG should show as an image in the same place where the other images appear. Because I have to use a browser here I expect tons of trouble on MacOS and iOS with Safari. E.g. Switching between SVG and normal images might not work properly etc. Please report.
- ⚠️ Be warned that the narrative - image associations don't synchronize, yet. That'll need a Kiosk update. 

Different Layout:
- the clip button in excavating / dayplans still works the same way as ever, Except that all images get a red marker that have the same date (as in day, not time) as the active narrative. So far only images that were added prior to the narrative (in terms of time of day) would have gotten a marker.

**Comment by luizaogs** [comment]
Clicking on the back button when in the calendar view takes me back to the narrative I was in, but it pops up the keyboard. Is that intended?

**Comment by luizaogs** [comment]
Also a weird thing that might be inconsequential but since I noticed it I mention it: clicking on the paperclip seems to get rid of some images in the list of dayplans, besides adding the red notation to those images associated with the narrative I'm on. For instance, if you go to LA and scroll down to the last narrative (so the oldest one), clicking on the paper clip will give me the association with the right images as far as I can tell, but the top images in the dayplans list disappear. When the paper clip is activated for this narrative, the list of dayplans stops on the photo of the black cat (my best friend, Leo). If I deactivate the paper clip, you'll see that the picture of Leo is actually not the first in the list of dayplans -- and that thus all of the images above Leo disappeared for some reason in the paper clip view.  Some images below Leo, including the ice cream and the pyramids, also disappeared when the paper clip was activated.

**Comment by luizaogs** [comment]
SVG issue reported in #2129

**Comment by luizaogs** [comment]
Other than those minor minor things, this is working well for me. And it is so cool!

**Comment by urapadmin** [comment]
### kiosk 1.4.13
- with this Kiosk version the narrative-file associations should sync!

**Comment by urapadmin** [comment]
### recording 14.10
- keyboard should not pop up when coming back from the narrative view
- I have battled the User interruption messages where I could. Better?
- clip button: The filter is by design. It assumes that when you look at a specific narrative all images later than that narrative are not of interest (while the clip button is on)

**Comment by urapadmin** [comment]
you can close this independent of the svg issue since that has its own ticket.

**Comment by luizaogs** [comment]
This is all working, including synchronization. And yes, the paper clip makes sense.

One last question before I close this. When leaving the narrative view, the paper clip is automatically activated (not sure if I just didn't notice that yesterday or if it's new today). Is THAT intended?

**Comment by urapadmin** [comment]
no, THAT is not intended...

**Comment by urapadmin** [comment]
### recording 14.10.1
- the clip should be back in the state where it was when entering the narrative-file view

**Comment by lbestock** [comment]
Is it possible this didn't make it into documentation? How did we communicate its existence to Anna, who loves it? Because #2796 is requesting something that is essentially this, and I can't figure out where to send @maychu16 to learn the feature to use it.
