### ISSUE TITLE
registration overview by trench / context - rethink the registration interface

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1816]
The interface is old and could be much better. The most important thing is navigation: 
- Navigation is covered by #1795 
- rethink it, make it more user friendly. 
- perhaps make it accessible in the Burger menu?
- Anna does not want to see the codes and only use the checkbox popup. While the codes need to stay in the background (sorting, filtering, Analyzing etc.) they could always be translated into real text and perhaps I can redesign the user interface to only show real text everywhere? 

### tracked:
- [x] #1931 
- [x] #1933
- [x] #1932

**Comment by urapadmin** [comment]
@lbestock @luizaogs 
Honestly, it isn't even all that bad. After navigation and perhaps some face lifting I am not sure what exactly to add here. Any thoughts?

**Comment by luizaogs** [comment]
I would looove a search button in the burger menu that I can use to see how specific cm were recorded previously (the current search works just fine for this purpose, I think).

**Comment by lbestock** [comment]
In mimicking workflow I am finding that I first mark everything home in the registration page. Then I am getting more detailed and I have artifacts in front of me so I can do initial measurements (and eat them since the artifacts are chocolate covered orange peels). It is THEN that I want to add most of my codes, but by then I'm in the CM record and not the registration pane. So it would be very helpful to be able to have the checkboxes, which I find much easier than typing the codes, available in CM if registration codes are configured to be editable there.

**Comment by lbestock** [comment]
The one substantial change I would make to the interface is what the title of the ticket says. Currently there is no way to sort or even see by unit or locus. That's because it was designed for Uronarti, where that information is part of the identifier. As one can clearly see in PVD now, with different identification methods that information is no longer clear in registration.  And since some projects separate CM by trench or locus, for instance putting everything from trench 4 on one table, and everything from trench 5 on another before the registrar attacks, we want to not only be able to see that but to sort by it and - if it works in the layout - be able to exclude all but one trench or all but one locus.

**Comment by urapadmin** [comment]
That's it?

**Comment by luizaogs** [comment]
I think so?

**Comment by urapadmin** [comment]
> The one substantial change I would make to the interface is what the title of the ticket says. Currently there is no way to sort or even see by unit or locus. That's because it was designed for Uronarti, where that information is part of the identifier. As one can clearly see in PVD now, with different identification methods that information is no longer clear in registration. And since some projects separate CM by trench or locus, for instance putting everything from trench 4 on one table, and everything from trench 5 on another before the registrar attacks, we want to not only be able to see that but to sort by it and - if it works in the layout - be able to exclude all but one trench or all but one locus.

this is covered by #1932

**Comment by urapadmin** [comment]
> In mimicking workflow I am finding that I first mark everything home in the registration page. Then I am getting more detailed and I have artifacts in front of me so I can do initial measurements (and eat them since the artifacts are chocolate covered orange peels). It is THEN that I want to add most of my codes, but by then I'm in the CM record and not the registration pane. So it would be very helpful to be able to have the checkboxes, which I find much easier than typing the codes, available in CM if registration codes are configured to be editable there.

this is covered by #1797

**Comment by urapadmin** [comment]
> I would looove a search button in the burger menu that I can use to see how specific cm were recorded previously (the current search works just fine for this purpose, I think).

covered by #1932

**Comment by urapadmin** [comment]
I think we can close this, right?

**Comment by luizaogs** [comment]
Hm. I just realized that I closed #1932 without asking @lbestock if she wanted a new ticket opened for adding the unit to the list here. I guess if yes this should be kept open?

**Comment by urapadmin** [comment]
I close this now.
