### ISSUE TITLE
unit image / narrative connection still not useful. Think harder.

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1823]
Came out of pasu. Anna tried to use the button that guesses a connection between dayplan and narrative but it did not work out.
- #89 

In part that is because the images don't have the right timestamp. When they are added in the evening but the narrative is written in the morning, they don't count anymore.

Think again. Do we really need a totally different user interface that actually allows straight references to images per narrative? That seems so over the top to me.

- there is also the idea of #1776. Might be related or there might be synergies to use.

**Comment by urapadmin** [comment]
@aes1884: I am going through the PASU requests from last year and this here was about the clip button that connects narratives with dayplan/unit images. You reported this as a problem. Now my question:
 
I could add images of the same day even if they got added later than the narrative. Would that improve the unit / narrative button?

**Comment by aes1884** [comment]
@urapadmin: For me, the ideal would be to be able link specific images/dayplans with specific narratives. Since we create more than one narrative a day and might update a dayplan multiple times over the course of the day it would be nice to be able to manually connect narrative to image/dayplan so that future readers of the notes can be clear regarding which visuals go with which descriptions. That said, being able to connect images from later in the day would be a big help.

**Comment by urapadmin** [comment]
### recording 14.9
- #1776 is the real solution
- the clip button above the dayplans now marks all images that are of the same day as the narrative, independent of the time of day. That should include images that have been added after the narrative.
