### ISSUE TITLE
issues with scrolling through su ceramic photos

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1833]
Version 13.6.1, issue that comes out of testing #1805 and that I have only come across in the su ceramics image containers. If adding several images to the same sherd, I am unable to scroll through the images as I am adding them. I noticed that, when adding images there, the numbers in the counter do not update properly -- for instance, I just added image 17 and the counter looks like this: 

![IMG_0310](https://user-images.githubusercontent.com/67970402/196014586-b062b25a-acfb-48e0-8965-0d9085492070.PNG)

In this case I am unable to scroll to others below image 17. Clicking outside of the container doesn't help. 

However, if I use the back arrow to go back to the FM start page and then go back into ceramics and go back to the same sherd, the image on top is now 1/17. This means that I can now scroll through the older ones. Screenshot: 

![IMG_0311](https://user-images.githubusercontent.com/67970402/196014595-cde29208-48ce-4268-bae0-cef267a6dd07.PNG)

**Comment by luizaogs** [comment]
Ah wait, I wasn't awake last night I guess. I can scroll UP but not down when adding images. So I guess the issue isn't the scrolling itself, but rather the fact that in this form -- unlike in locus and collected material photos -- the image added is the last one rather than the first, which is confusing to the user especially when the other forms all work differently.

**Comment by urapadmin** [comment]
That might be the same in warecode pottery

**Comment by luizaogs** [comment]
It is the same in warecode pottery.

**Comment by urapadmin** [comment]
### 13.7.6
I must disagree here (and perhaps everywhere else). If the new image gets added as the first image in the list it also gets the number 1/x. That is to me even more confusing because why is it not getting x/x? You might be confused by the scrolling but if you use the back and forth buttons I get more confused if I have to go to the next after I added one but cannot go to the previous. I think it is a particular strange thing here and in warecode pottery that you do not see a list of images but only exactly one? I have not changed this one but I am open to reassessing all of the image containers as to whether or not we should switch to adding a new image always at the end.
