### ISSUE TITLE
creating new cm sends me to photos rather than basics tab

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1886]
Comes out of testing #1868.

When I create a new cm in the cm layout using the plus button between the two arrows, I get sent to the photos rather than the basics tab of the new cm. So not a big deal, but unexpected since I would probably want to input the cm details before adding a photo.

**Comment by luizaogs** [comment]
Oh huh wait, apparently this is not the case every time. It happened in the first two cm that I created, but now it does not happen any longer.

**Comment by urapadmin** [comment]
That should not happen. I wonder it it might have to do with a change in material.
What type of collected material are we talking about? bulk? small finds? That can matter, too.

### 13.6.8
However, since I have no idea what could have triggered it, I am now explicitly activating the first tab no matter what after creation.

**Comment by luizaogs** [comment]
Looks fine now (in all types).
