### ISSUE TITLE
kiosk: new user stuck on "please try a fresh login" page

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1921]
So in 1.2.9 I can now create a new user without an error, but I cannot get them past the "please try a fresh login" page (screenshot below) and clicking on Hub in the burger menu doesn't work either. I've tried setting the test user as an operator and it didn't work, then I did just field_worker and that didn't work, and then I tried field_worker, operator and that didn't work either. 

<img width="1512" alt="Screenshot 2022-11-08 at 7 56 07 PM" src="https://user-images.githubusercontent.com/67970402/200718392-2d09979a-2e45-403a-a31f-90ed5d7c4edd.png">

**Comment by luizaogs** [comment]
Oh wait, it totally gets weirder. When set to both field_worker and operator I cannot access the Hub through the burger menu with the test user, but I can get into administration??

**Comment by luizaogs** [comment]
And bugs and features and director's view and the file repository, too. The only one I can't actually get to is the Hub.

**Comment by urapadmin** [comment]
> Oh wait, it totally gets weirder. When set to both field_worker and operator I cannot access the Hub through the burger menu with the test user, but I can get into administration??

On PVD "operator" gives you access to the administration because it has the privilege "enter administration"

The reason why you cannot get into the hub is because both field_worker and operator are missing the "download workstation" privilege, which is the one that makes the Hub appear at all.

So this is all because of former testing on PVD.

**Comment by urapadmin** [comment]
> So in 1.2.9 I can now create a new user without an error, but I cannot get them past the "please try a fresh login" page (screenshot below) and clicking on Hub in the burger menu doesn't work either. I've tried setting the test user as an operator and it didn't work, then I did just field_worker and that didn't work, and then I tried field_worker, operator and that didn't work either.
> 
> <img alt="Screenshot 2022-11-08 at 7 56 07 PM" width="1512" src="https://user-images.githubusercontent.com/67970402/200718392-2d09979a-2e45-403a-a31f-90ed5d7c4edd.png">

I suspect at this point your "test" user did not have the privilege to enter the Hub. Since the hub is configured to be the start page for PVD you immediately run into this. That's not optimal (in case we'd have users that are not allowed to see the hub but are allowed to browse the file repository) but it isn't all that relevant, currently. Should we run into this in a real world scenario I would make the start page user-specific. I'll add this as an idea: #1923

**Comment by urapadmin** [comment]
I also should either right a thingy on users and privileges or make a video. For the time being all we have is the wiki: [https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=kiosk_privileges](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=kiosk_privileges)

**Comment by urapadmin** [comment]
for you to close

**Comment by luizaogs** [comment]
Ha I even read the wiki thing on privileges, but clearly not closely enough. This seems fine -- I added the download privilege to the user and now I can get to the hub.
