### ISSUE TITLE
CSV import to make coordinates from the GIS available in the recording system

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1986]
MKAP needs to be able to link various types of information about their control points. Some of that information will be generated in the recording system, and some outside of the recording system, and it all needs to be visible in the recording system. This ticket comes out of #1980 and the discussion Didi, Luiza, Lutz, and Laurel had on 21 Feb 23.

Control points receive discrete names. They live in the GIS as points with locations, but they also need to be found again on the ground, sometimes after considerable time. The recording system on the iPad needs to be able to display together:

- point names (can be created first either in the GIS or in the recording system - is the thing that allows the two to be connected and so needs to be input identically in both places)
- point coordinates (can only be created in the GIS by shooting the point in with the GPS - accuracy is important so we might test the iPad as a GPS for a rough point but that is highly unlikely to be precise enough alone and would be a separate test field)
- photo (can only be created in recording)
- description/text blob field (created in recording)

Where should this live and be accessed in the recording? Is it most useful as a tab in a unit, where all the control points associated with a unit (whether survey or excavation) are present? Or as an overall list, maybe in specialists?

My (@lbestock ) initial thought is that a single list in the specialists tab is preferable for two reasons. One is that sometimes one will want to go locate these things en masse, not as part of a unit-based strategy, and so having to go into units is a pain. But the second is even more compelling: not all control points will be associated with a unit at all. This is where, for instance, one should store one's backsite points, and those are necessarily as FAR from the place you are working as practicable. I can't tell you how many times I have wasted hours at the beginning of a season hunting for backsites, with slip of paper in my hand with the coordinates and no photo at all, just my own memory of approximately where it was located out in an expanse of desert. 

That brings me to other potential uses of a similar functionality where coordinates derived from the GIS are moved into the recording system so that they can be seen by a human eye on the iPad. I can think of two immediately, three if we include finding backsites (but that's in the same interface I think):

1. Finding trench boundaries. MKAP is going to be working on a grid. Units may be set up on grid coordinates to capture squares of the grid (common at many sites that aren't in fortresses or villas). The corners of that unit are then known in the GIS before they are known on the ground, and before excavation can begin stakes need to be set at those points and string strung. If the grid coordinates as determined on the GIS had already been transferred to kiosk then one opens one's new unit recording and wham, it tells you where to fiddle around looking for the point, much as with control points.
2. Elevations. For a lot of elevation stuff I would expect to be in the GIS and not the recording, but sometimes it is very useful in the field to know, say the elevation of the top of a context (for instance when one is digging sondages and hits a layer that looks familiar, knowing if it is at the same elevation is helpful). The way people take elevations is variable and this is a mess we have thought about some in the past. We have discussed having a difference between an elevations tab that is control point, offset, calculated elevation based, or one that is coordinate based. Right now it's a mush and projects have to define how they use it. For those that use coordinates (deriving their elevations from the GIS) it was always ridiculous to think of hand inputting those data. But if we have a way of moving coordinate data from the GIS into the recording system, this is another place where it would make sense to utilize it.

### related tickets
- [x] #2009 
- [x] #2008 
- [x] #2014 
- [x] #2013 
- [x] #2010 
- [x] #2007

**Comment by luizaogs** [comment]
I totally agree that a list in the specialists tab seems preferable, but then I wonder if making it possible to link markers to units (I guess kinda like features can be linked to units) would be useful? If they are attached to a unit, though I know that most probably won't be.

**Comment by didi-elbehaedi** [comment]
I second both @lbestock and @luizaogs about the list of control points being housed in the specialists tab, if this is something that is easy and doable! I can certainly confirm that many of the control points that we'll collect in the field won't be associated with an excavation unit or feature per se, so this seems like a good solution?

**Comment by lbestock** [comment]
There is already a datum field in the measurements tab of contexts. It's just elevation. We could make that full coordinates and have the name of the control point/datum there and it could self-populate with the information from the list of control points in the specialists tab if and when a named control point is of relevance to a locus and being used to take elevations in that unit. I think that would work better than linking to a unit in the list in specialists tabs. The control point is only relevant to the unit if it is being used to measure off of, right? And then it's even possible that different loci in the unit are being elevated from different control points near the unit, so keeping it at locus level and showing it only when it is being used makes some sense. The point is not itself a part of the unit and its location doesn't help describe the unit. It is only relevant when relation to the point is a factor for describing something, and that's a locus elevation not a unit.

I am also now remembering that KHPP doesn't HAVE a GIS and thus we shouldn't make too many assumptions on the basis of expecting all projects to generate even geospatial data in the same ways.

**Comment by lbestock** [comment]
@urapadmin Here - use case as discussed, with the need for photos of points in some cases. Not just a list.

**Comment by urapadmin** [comment]
so my strategy will be this:
- a list of coordinates as a new surveyor module
- each coordinate can have a description and images attached to it
- coordinates have a name and a category - the latter so that one can group them
- coordinates have decimal longitude, latitude and elevation. The unit of the longitude and latitude is set in the configuration, the unit of the elevation as well, but can be different from long/lat. Means: All coordinates of a single project are of the same unit.
- while it is possible to type and alter coordinates in the recording system, it is not fun, hence:
- Kiosk gets an import module for coordinates. Coordinates must have a name, can have a pair of longitude and latitude and can have an elevation. They can also have a category.
- if an imported coordinate is already known under that name it will be updated. If there isn't already a coordinate for the name a new coordinate record is created. That way a coordinate can be named already in the field on an ipad, photos can be shot of it and the coordinate is assigned later during import.

**Comment by urapadmin** [comment]
@luizaogs / @didi-elbehaedi: Is there a connection between such coordinates and [https://github.com/arch-kiosk/arch-kiosk-office/issues/1980#issuecomment-1462113880](https://github.com/arch-kiosk/arch-kiosk-office/issues/1980#issuecomment-1462113880)?

**Comment by luizaogs** [comment]
Yes. That form, which is specifically for photogrammetry, includes a list of markers. Many of those markers will have coordinates (those are important for building the 3D model). 

I’m not sure if the photogrammetry analysis module would need to be separate from what you’re envisioning here - the main difference I can think of is that there would need to be a way to add an image to the category, too, since one usually sketches the area being modeled in order to indicate where the markers were placed (that’s what the sketch is for in the paper form). Perhaps also making it possible to add a description to the category would be enough in terms of adding the other relevant information on the form (locus and feature numbers relevant to the model, etc).

**Comment by urapadmin** [comment]
### Kiosk 1.4.2.0 / recording 14.1
The first tack on this is rolled out: 
- There is a new UI in the recording to enter coordinates (aka points). You find it on the start page in the specialists / surveyor section
- You can attach images to every coordinate
- coordinates can (and should although it is optional) have a category
- the name of a category should be unique. That's why that name is an identifier and has an identification method (currently simply set to free input9
- because it is a identifier you can search for it like with any other archaeological identifier
- for the same reason you can search for the point's name in Kiosk's file repository and get the images attached to it
- although you CAN enter longitude, latitude and elevation in filemaker, the idea is a different one: You enter a point here and import the actual coordinate values later. But you can also import NEW coordinates in Kiosk and would find them here and can attach images afterwards. Whatever suits your workflow best.
- in FileMaker you can delete, sort and filter coordinates

In Kiosk you find a new main menu item "point repository". It is basically a sortable list of all known points. 
- You can drop a file onto the upload zone and have it uploaded and imported. The file has to be either a CSV or an Excel file. I recommend CSV because Excel always outsmarts itself when it comes to datatypes. Please, archaeologists in the world, uninstall your Excel!
- The way I have configured Kiosk currently the file must have the data in each line organized exactly in the following order:
  - point name
  - Latitude
  - Longitude
  - elevation
- here is an example with exactly one point: [LK's Points.csv](https://github.com/arch-kiosk/arch-kiosk-office/files/11055738/LK.s.Points.csv)
  
- the first line of a file is skipped (whatever is in there, usually it is the headers, but they are NOT interpreted). 
- the latter makes it possible to import either the "Sample.GNSS.Points.csv" or the "Sample.GNSS.Points_RAW.csv" file that Didi gave me as a sample. Both have the same result. For Kiosk it is not necessary to brush up the raw file. 
- As for the category for the points: In the way it is currently organized the filename of the file you upload will automatically be the category for each point. So if you upload "Sample.GNSS.Points.csv" all points will be in category "Sample.GNSS.Points". 
- A point is only unique within its category. So if you upload a point P1 with the file "cat1.csv" and you already have a point "P1" in the database BUT in category "cat2" you will get a NEW point P1 in category cat1. On the other hand if you upload a file cat2 with the point P1, the existing point P1 in category cat2 will be updated with the coordinates in the uploaded file.

- it is currently not configured but we could also import a category from an additional column per point or the importer could take the category from a first line in the uploaded file.
- also not configured on PVD, currently: The uploaded file could have a description column per point that imports, well, the description.

**Comment by lbestock** [comment]
Wow for fun trying to get my coordinates from my phone and it sucks. Degrees minutes seconds so I can't enter it, and for sure the elevation isn't very accurate. And it's in feet unless I switch my whole phone to be in a region where metric is used.

**Comment by urapadmin** [comment]
- found a first issue: When there is NO category for a point in Filemaker it comes out as "None" in Kiosk.

**Comment by lbestock** [comment]
I can get decimal coordinates (which are way better anyway) from googlemaps, but that doesn't give me the elevation. 
I have to use my phone; I have no other gps at home. And doing it without real coordinates? Brrr.

**Comment by lbestock** [comment]
Note on above instructions (I don't think it's wrong, I think you just typed category in your instructions when you meant coordinate, but I'm not 100% sure so I won't edit them): the identification method is for the coordinate identifier, not for the coordinate category.

**Comment by lbestock** [comment]
Hm a question also for other places with filters. If I am in a record, and filter for a result that would not include that record, I nonetheless stay in the record. The list on the left reflects the filtering but I'm not kicked out of the one I am in. Is that expected?

**Comment by urapadmin** [comment]
> Hm a question also for other places with filters. If I am in a record, and filter for a result that would not include that record, I nonetheless stay in the record. The list on the left reflects the filtering but I'm not kicked out of the one I am in. Is that expected?

That should not be the case. I must drop the current selection when a filter is applied.

That it is wrong here does not necessarily mean the same thing happens in other places. Every filter is a handmade unique thing because FileMaker is not for software development. So please make single tickets for filter issues in other places (not here).

**Comment by luizaogs** [comment]
Sooo, do I test this? Or is it done for now? I don’t want to make a mess.

**Comment by urapadmin** [comment]
> Sooo, do I test this? Or is it done for now? I don’t want to make a mess.

of course you do. It is also not only about testing whether it works as I intended. Most important is the question: Does it do what you guys wanted? Is it useful that way or does it need adjustment?

**Comment by urapadmin** [comment]
### Kiosk 1.4.2.1
To test at least the first part here you need to allow the recording to have an empty category (see below under recording):
- if a point does not have a category it isn't showing any (was 'None' before)

This can't be tested with the current configuration because the category is taken from the filename (hence you cannot have NO category):
- if a point does not have a category it gets update only by a point in an import file if that one doesn't have a category, either

That's just the standard (and was already okay in the last version, but who knows if I screwed it up now?):
- if a point does have a category it gets updates only by a point in an import file that has the same category and point name

### recording
- if the config key general/coordinate_allow_no_category is yup (default is nope) coordinates can have an empty category. By default we want coordinates to have a category.

**Comment by luizaogs** [comment]
> * Except for "free input" only a numbering strategy that draws from a identifier list would make sense. Who wants to test that? You'll find a new "coordinate" item under "identification methods" in the configuration in the recording.

Eesh, @lbestock do you want to test this part? Unless either of you want to refresh my tired brain on how to actually get the identifier list to work for this...

**Comment by lbestock** [comment]
Oh ha I actually tested that last night just for fun before it was flagged as difficult. And it worked just fine.

**Comment by luizaogs** [comment]
Ah ok great!

**Comment by luizaogs** [comment]
Ok Lutz, I tested everything before the 1.4.2.1 update above because I don't think that has been released. It seems to be working just fine, minus the couple of tickets I opened. And I think it does what it needs to do, though I have not run it by Didi yet because she is no longer in Edfu. 

But: for photogrammetry I think we need the categories themselves to have information attached to them, as I mentioned above, because they would need their own sketch/image and description. But for surveying and points themselves this seems great, and if you guys aren't looking to support photogrammetry right now this should suffice.

**Comment by luizaogs** [comment]
Ha well I clearly did not test importing blank elevations...

**Comment by luizaogs** [comment]
> Ok Lutz, I tested everything before the 1.4.2.1 update above because I don't think that has been released. It seems to be working just fine, minus the couple of tickets I opened. And I think it does what it needs to do, though I have not run it by Didi yet because she is no longer in Edfu.
> 
> But: for photogrammetry I think we need the categories themselves to have information attached to them, as I mentioned above, because they would need their own sketch/image and description. But for surveying and points themselves this seems great, and if you guys aren't looking to support photogrammetry right now this should suffice.

Ok yes, I just talked to Didi and she agrees with everything I said here. Looks great, and we would just need to add a couple of things for photogrammetry. (We just noticed that there are QR codes for points, too -- so good!)

**Comment by urapadmin** [comment]
> I also tried importing a csv last night with blank elevations, and it was rejected. I didn't know that was a point to test or configurable at that point, but I can attest that in the out of the box configuration Lutz gave us, blank (or non-numerical) cells resulted in a failure to import.

what does "empty" mean? What was the error message and please show me your csv.

**Comment by urapadmin** [comment]
> > Ok Lutz, I tested everything before the 1.4.2.1 update above because I don't think that has been released. It seems to be working just fine, minus the couple of tickets I opened. And I think it does what it needs to do, though I have not run it by Didi yet because she is no longer in Edfu.
> > But: for photogrammetry I think we need the categories themselves to have information attached to them, as I mentioned above, because they would need their own sketch/image and description. But for surveying and points themselves this seems great, and if you guys aren't looking to support photogrammetry right now this should suffice.
> 
> Ok yes, I just talked to Didi and she agrees with everything I said here. Looks great, and we would just need to add a couple of things for photogrammetry. (We just noticed that there are QR codes for points, too -- so good!)

ja, this was not meant to solve the photogrammetry question. I'll look into that next. I wanted to have this done before Laurel talks to Kathy Kearns so that she can check whether it solves her needs, too.

**Comment by lbestock** [comment]
Recreated since the files didn't exist anymore, but the same with the same (looks totally proper) error messages.

![image](https://user-images.githubusercontent.com/49291909/227784839-53e806b7-dc99-4029-81b4-5754ff09a0ae.png)
![image](https://user-images.githubusercontent.com/49291909/227784886-024f652f-9754-4886-8079-6dd2abad6509.png)
[Qbacksites.csv](https://github.com/arch-kiosk/arch-kiosk-office/files/11072012/Qbacksites.csv)
[Xbacksites.csv](https://github.com/arch-kiosk/arch-kiosk-office/files/11072014/Xbacksites.csv)

**Comment by luizaogs** [comment]
See #2013 , the 1.4.2.1 update is not yet working.

**Comment by urapadmin** [comment]
> Recreated since the files didn't exist anymore, but the same with the same (looks totally proper) error messages.
> 
> ![image](https://user-images.githubusercontent.com/49291909/227784839-53e806b7-dc99-4029-81b4-5754ff09a0ae.png) ![image](https://user-images.githubusercontent.com/49291909/227784886-024f652f-9754-4886-8079-6dd2abad6509.png) [Qbacksites.csv](https://github.com/arch-kiosk/arch-kiosk-office/files/11072012/Qbacksites.csv) [Xbacksites.csv](https://github.com/arch-kiosk/arch-kiosk-office/files/11072014/Xbacksites.csv)

I move this to a new ticket: #2014

**Comment by urapadmin** [comment]
> Ha well I clearly did not test importing blank elevations...

and you mustn't because it isn't allowed unless a project decides to do without elevations in general.

**Comment by luizaogs** [comment]
Do we close this now?

**Comment by urapadmin** [comment]
I'll do it

**Comment by urapadmin** [comment]
does somebody have a mind to add this to the directors/admin FAQ? It is mentioned nowhere and so hardly anybody would know how to use it and for what.

- There is also #2761 which we have not yet reecorded

**Comment by lbestock** [comment]
Added. Not my best description, but it exists with instructions.
