### ISSUE TITLE
floating file picking rules that no longer belong to a port

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2004]
In testing #2001 I realized that we currently have a bunch of file picking rules in PVD that are now irrelevant because those ports no longer exist in the hub (see the list of rules below, ports file picking and new port no longer exist). I am not sure how applicable this is beyond a testing scenario, but I guess I expected that those rules would have disappeared once the port was deleted.

<img width="1483" alt="Screenshot 2023-02-28 at 7 17 07 AM" src="https://user-images.githubusercontent.com/67970402/221865668-dcda4a7f-22a6-4bf5-abff-ab68f3a1af00.png">

**Comment by urapadmin** [comment]
That is by design. A port exists as soon as a dock in that port exists and as long as there is any dock in it. When that is the case, the file picking rules apply.
If I deleted all the file picking rule as soon as I delete the last dock in a port, I'd have to type them in again once the port is being used again. I find that more damaging.

E.g. ipad yellow is used in dock "Trench A" that has rules to reduce images to that thrench. Tomorrow iPad yellow is being used in "Trench B" and so Trench A does not have a dvice on that day. On day three it is back at Trench A and poof are the Trench A file picking rules.

**Comment by urapadmin** [comment]
This is also important so that we can prepare projects with all kinds of file picking rules in advance - before they have created any docks at all.
