### ISSUE TITLE
kiosk image warning

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2011]
Well I was going to test the newest update of #1986 but I just got the warning below after preparing my workstation so am following instructions and letting you know before continuing: 

<img width="1490" alt="Screenshot 2023-03-24 at 9 29 24 PM" src="https://user-images.githubusercontent.com/67970402/227622091-52318529-e4f2-4751-bdb6-c9e908cf6b8c.png">

**Comment by urapadmin** [comment]
@lbestock: This might be interesting to you, too.

That is presumably okay in your case because you were testing very quickly. In, new image, out, upload can indeed lead to this warning. If you see it frequently or in cases where you are sure you did not add or modify an image, alert me to it again. Or, particularly, if the number is higher (1.0 means we are talking about exactly one image here).

**Comment by luizaogs** [comment]
I thought it was odd because I hadn’t tested in 2 hours or something so I hadn’t modified anything at all.

**Comment by urapadmin** [comment]
well, in that case don't touch your dock (you can use a different one). I'll have a look at it later (currently traveling).On 25. Mar 2023, at 13:13, luizaogs ***@***.***> wrote:﻿
I thought it was odd because I hadn’t tested in 2 hours or something so I hadn’t modified anything at all.

**Comment by luizaogs** [comment]
Will do.

**Comment by luizaogs** [comment]
Hmm and now my download in my other workstation is pending forever so I will stop messing around and will finish testing the coordinates stuff once you are back.

**Comment by lbestock** [comment]
Oh wow it looks like your workstation is still spinning!

**Comment by urapadmin** [comment]
that's a typical sign for a downed Master Control Program. For unknown reasons the Brown server got restarted.  
It is up and running again,

**Comment by luizaogs** [comment]
Yep.

**Comment by urapadmin** [comment]
looked into the original issue here. You are in Chicago, I suppose? The image was modified at 16:09 local time and the warning was generated at 15:29, so before that. That is indeed very recent from the server's perspective :o) 
Can the timezone be our issue here? The warning is itself a very recent modification, so you would not have seen it prior to kiosk version 1.4.2. But I am a bit surprised that you did not run into it before and constantly. 

To explain: The warning measures if any images have been modified within the last 5 minutes. In a real scenario that is highly unlikely. I am not sure I want to address this at all since it is a timezone issue and the TimeZone problem is on the list of really big things to do, anyhow.

**Comment by luizaogs** [comment]
I'm in Egypt so I guess timezone could be the issue still, yes.

**Comment by luizaogs** [comment]
Oh wait but I think my workstation is Chicago. Anyway, yes, the answer is the same.

**Comment by urapadmin** [comment]
That does not fit. Typical case of an expectation fallacy on my side (You are ahead of the PVD server not one hour back). I'll have to try harder.

**Comment by luizaogs** [comment]
The workstation's timezone is Chicago, though. GMT-6. I should have changed it when I got here but forgot so I've been telling FM to change it to the server's timezone.

**Comment by urapadmin** [comment]
I saw that, but it does not matter in this case. The TMZ setting on workstation level only compensates if you actually change your images in a TMZ that is earlier than the server's. You are actually ahead of the server in Egypt. Something else is afoul...

**Comment by urapadmin** [comment]
> The workstation's timezone is Chicago, though. GMT-6. I should have changed it when I got here but forgot so I've been telling FM to change it to the workstation's timezone.

oh, wait, what does that mean? You have been telling FM? Does that mean you have changed your local time on the ipad?

**Comment by luizaogs** [comment]
No. I get this warning: 
<img width="809" alt="Screenshot 2023-03-26 at 6 47 39 PM" src="https://user-images.githubusercontent.com/67970402/227791044-d4efdd19-c5f1-4dca-bece-6e341c16b75b.png">

And after clicking on "set to local timezone" I get this: 
<img width="475" alt="Screenshot 2023-03-26 at 6 47 53 PM" src="https://user-images.githubusercontent.com/67970402/227791078-501263c6-1a4b-43d1-805b-7df39e9f848e.png">

**Comment by urapadmin** [comment]
ah! I see. I forgot about that one.

**Comment by urapadmin** [comment]
- For reference: Original issue for this one was #1996

**Comment by urapadmin** [comment]
I honestly don't know what is going on here. The warning did not come after the image was added and then the workstation prepared for the field. It came when the workstation was prepared for the field once more. Since nothing happened between those two preparations I am not even sure why that was necessary. 

I can confirm that the image record is correct and the images did not actually get a new modification date (which was the original issue in #1996 that made me add this kind of warning). So in this case the warning should not have come up. But it did. So I am confused. We must keep an eye on this.

**Comment by urapadmin** [comment]
### Kiosk 1.4.2.2
- a slight improvements of logging behind the scenes so that I have better information next time

**Comment by luizaogs** [comment]
Nope. I have not touched file picking.

**Comment by urapadmin** [comment]
okay. I am lost for now. We have to wait if it reappears and I have more data.

**Comment by urapadmin** [comment]
I close this due to inactivity
