### ISSUE TITLE
Coordinate import: Importing empty values

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2014]
Recreated since the files didn't exist anymore, but the same with the same (looks totally proper) error messages.

![image](https://user-images.githubusercontent.com/49291909/227784839-53e806b7-dc99-4029-81b4-5754ff09a0ae.png)
![image](https://user-images.githubusercontent.com/49291909/227784886-024f652f-9754-4886-8079-6dd2abad6509.png)
[Qbacksites.csv](https://github.com/arch-kiosk/arch-kiosk-office/files/11072012/Qbacksites.csv)
[Xbacksites.csv](https://github.com/arch-kiosk/arch-kiosk-office/files/11072014/Xbacksites.csv)

_Originally posted by @lbestock in https://github.com/arch-kiosk/arch-kiosk-office/issues/1986#issuecomment-1484125276_

**Comment by urapadmin** [comment]
The Xbacksites.csv is wrong. It actually contains an x in line 2, column 2.

**Comment by urapadmin** [comment]
As for an empty elevation. I am not sure why we would want to allow for that. If a project in general does not deal with elevations, I can configure it that way (in that case the elevations column would not be needed in the CS V file). 
But if we expect elevations then an empty elevantion is as wrong as an empty latitude or longitude.

**Comment by lbestock** [comment]
But this is all what I expected. I know the x was wrong, I wanted to make sure different kinds of wrong csvs were rejected, and they were. Hence I didn't report any of his until asked, I really thought it worked properly, even told me where the problem was so I could correct my file.Sent from my iPadOn Mar 26, 2023, at 3:04 PM, kioskadmin ***@***.***> wrote:﻿
As for an empty elevation. I am not sure why we would want to allow for that. If a project in general does not deal with elevations, I can configure it that way (in that case the elevations column would not be needed in the CS V file).
But if we expect elevations then an empty elevantion is as wrong as an empty latitude or longitude.

**Comment by urapadmin** [comment]
so you may close this
