### ISSUE TITLE
FM configuration: preprocessing only works if ceramics are called ceramics

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2068]
It is so great to have new projects and learn new things.
KAMBE calls ceramics pottery. I will try to talk them out of that anyway, but meanwhile I used pottery in configuring their database. And it didn't work and confused me. I had pottery instead of ceramic in the valuelist for materials. And I had pottery in the configuration key "show only this material in pottery selection" (OK ha that is amusing - I just caught that that KEY is called pottery, not ceramics, which also explains why I didn't find it searching...)

All my other settings regarding ceramics modules were as they were for KHPP, where we had after some effort configured things so that preprocessing was on and processing was off. 

So I was surprised when I didn't get preprocessing with my above settings. To make sure, I changed only those two things, the valuelist and the "show only this material" to ceramic. Voila. Now I have preprocessing. So lesson: one cannot have preprocessing if it isn't called ceramic but it isn't clear why that is the case to a configurer.

**Comment by urapadmin** [comment]
that is what I tried to explain about the id in the module section. The id "ceramics" has to be "pottery" and that id has to have the value for the ceramics module. So you have to change the id "ceramics" to pottery. But I suppose you can't because ids can only be changed by the developer. So go to admin and make yourself a developer by turning on the developer mode. Then you should be able to change the id to pottery.

**Comment by urapadmin** [comment]
have you had success with this?

**Comment by urapadmin** [comment]
I see, you have instead talked KABME out of "pottery".
I will close this then since it is moot now.
