### ISSUE TITLE
dock preparation issue

### ISSUE THREAD

**Issue by lawarden** [arch-kiosk/arch-kiosk-office#2086]
![image](https://user-images.githubusercontent.com/132224283/235788858-e5eaa510-5c62-489c-bdef-d6eeae265b93.png)
![image](https://user-images.githubusercontent.com/132224283/235788955-9d5a4e50-c04d-4a3f-bf97-e09456c366b4.png)

When trying to prepare a dock for download, I got the following error message. It is unclear how I should resolve it so I can get the database on this iPad.

**Comment by urapadmin** [comment]
hm. I have not seen something like that before. I would try to repeat it.

**Comment by lawarden** [comment]
Done and worked.

**Comment by urapadmin** [comment]
It looks in the code as if a dock that was about to do something got cancelled in a very early state. 
Can be due to an accidental double click or so. 

Looks scary - totally benign. Whenever you get a somewhat cryptic message that does not seem to be made to be understood - try again. We call such things "hiccups".
