### ISSUE TITLE
filemaker: start / stop qr codes for sequence import in the recording app

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2138]
When turning up a QR Code you have to select whether it is for a

- single shot or
- a sequence marker

Single shot qr codes are the ordinary ones that get imported by the Ton or upload import,
sequence marker qr codes mark the start and end of a sequence.

**Comment by lbestock** [comment]
Might be better to reframe as in the shot vs not in the shot, marking the beginning or end of a sequence. I find "single shot" confusing because it's still very possible and desirable to have a QR code photo board in the frame of multiple consecutive shots.

**Comment by urapadmin** [comment]
the sequence marker qr codes need a visible sign that they are indeed sequence markers. 
I can imagine that somebody stars a sequence with a sequence marker and then ends it accidentally with a single shot qr code. The sequence import will ignore that but to find out why afterwards it is important to see in the photo that the closing qr code isn't a sequence marker.

**Comment by lbestock** [comment]
Disagreeing again on the what to call it front, because the people using it in the field might never touch the import function or have any idea how it works and still need to know what to do with the iPad. We want a terminology that helps people to use it properly in the field. Maybe we can come up with something that hits both, or has two terms, one prioritized on the iPad for the person putting it in the shot, and one at the import for the person bringing into Kiosk. "Photoboard" (for in-frame, single image recognition in import) is what we really mean.

On distinguishing the QR codes, the QR code for sequence shooting can actually be quite small on the screen of the iPad. That would make it unreadable as a photoboard shot, and that it would be so would also be clear to whoever is using the iPad and so they would be unlikely to mistake it in that direction.

**Comment by urapadmin** [comment]
If people shooting qr code photos in the field don't actually know what they are doing and what they are doing it for, this will go wrong anyway. How would they know why to use "in the shot" or "not in the shot"? Shooting in sequences needs organization and thinking. I still maintain that calling it single is more descriptive for what it is for. Given that there will be two buttons, one saying "sequence marker" and a description of both, I stick with my own terminology. Unless you come up with something better quickly.

**Comment by lbestock** [comment]
Pax :) You may have it. I will make an actually short video explaining it to field people and then it's up to them.

**Comment by lbestock** [comment]
Totally works! Neither type of QR code was recognized by the 1.5.0 Kiosk - the error message was the same for all my images, that there was no recognizable context or a missing QR code.

Creating them of course works, too, or I couldn't have tested that old Kiosks can't accept the import. This is a game changer. 

I would still make the visual distinction between the two types much more obvious, but the intro explanations are helpful and the icons, too.

**Comment by lbestock** [comment]
Tiny bug:
The "close" button on the intermediate screen does not work. I mean the screen where you choose which type of QR code you want. To get out of that screen one must select a QR code type, then close the QR code the normal way.

**Comment by urapadmin** [comment]
### recording 15.1.6
- closing the selector window should work now

**Comment by luizaogs** [comment]
MCP is down, Lutz, I believe.

**Comment by urapadmin** [comment]
upps. Forgot to restart it. 🧇

**Comment by urapadmin** [comment]
should be back.

**Comment by luizaogs** [comment]
Yes, with graduating spider and all :)

**Comment by urapadmin** [comment]
but this time for real, okay? No touching your dissertation again for at least 3 weeks :o)

**Comment by luizaogs** [comment]
🫡
