### ISSUE TITLE
recording: images coming back to database as .webp

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2156]
Hm. The images are appearing just fine in the file repository but I'm getting weird stuff when downloading the database again: the images don't come back and they have a .webp extension. Could it be because of drag and drop on my Mac? But that usually works fine and anyway the files have their proper file types (HEIC and jpg in the file repository) so I don't know. I'm also not getting that error in the logs so I'm not sure this is even related.

If you want to check the logs or the files, the last synchronization I did was at 4:15pm Chicago time. The images are bc1f9e72-6844-41fe-b44a-2a07712b3a7e and 9a7a7eaf-f99e-471a-bd06-2af838eadf29.

<img width="1023" alt="Screenshot 2023-06-01 at 4 22 08 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/05a26f59-c042-4837-85b3-edaa5a6dab57">

_Originally posted by @luizaogs in https://github.com/arch-kiosk/arch-kiosk-office/issues/1184#issuecomment-1572803760_

**Comment by urapadmin** [comment]
Hm. the question I ask myself currently is: Why does it surface just now? Filepicking is set to "small" or "tiny" and those are indeed webp thumbnails. Older images would not get converted if they were already there as JPG thumbnails but all new images would get a webp thumbnail and that is the one being transported to the recording app due to file picking. 

Hm

**Comment by urapadmin** [comment]
okay, this is all fine. I have changed the file picking rules on test and after that the correct thumbnails were back.
This is also not an issue for field projects as long as they don't use a "tiny" file picking rule.
