### ISSUE TITLE
File Manager: "back" should go back to the module that triggered the File Manager

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2158]
If a module jumped straight into a certain topic then going back should take the user back to that module and not back to the root of the file manager.
Perhaps a cookie or so can be used?

**Comment by urapadmin** [comment]
### Kiosk 1.5.2
- after downloading a report one can go back to the Hub now.
- check that after having done that once going to the file manager through administration works normally (as in: when entering a topic the back button points back to the root for the file manager)

**Comment by luizaogs** [comment]
This is working, only when I go into the file manager through administration the back button is labeled with the topic, rather than "file manager" (which is what I expected). Is that ok? 

<img width="1273" alt="Screenshot 2023-06-04 at 11 54 00 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/ba528e41-161e-4463-83ce-2f5898bf8502">

**Comment by luizaogs** [comment]
Alrighty then.
