### ISSUE TITLE
CM filter: missing "type" dropdown in unit CM list

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2164]
Testing PASU and touching everything, as requested, and I realized that the filter in the unit CM list lacks the dropdown for type. The dropdown for material is there where it belongs. Typing in the type works, but I assume you meant to include a dropdown?

![IMG_0347](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/09ca4d1d-70ef-4bb0-af43-43157784377f)

**Comment by urapadmin** [comment]
that is not the case because the type here is a combination of types: 
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/074b12a6-7f93-47a1-ac73-4a23c644205f)
So you can type "pot" or "broke" and get the broken pots.

BUT: this pointed me to a real bug: This column was influenced by the new column setting in the registrar module. That must not be the case. Here it should always show the combination of types as shown in the picture. In registration it depends on the setting for the configurable column.. I reopen #2141

**Comment by urapadmin** [comment]
### recording 15.1.6
- Independent of the column setting in registration this here should always show the combination of types as shown in the picture.

**Comment by luizaogs** [comment]
Ah. I see.

**Comment by urapadmin** [comment]
15.1.6 has not been rolled out, ye, has it?

**Comment by luizaogs** [comment]
We're currently on 15.1.6. Was this supposed to be .7? But it's already working.

**Comment by urapadmin** [comment]
ja, I must have mixed up versions then. The filter was already working properly but the type column was showing the wrong values depending on how the column was set in registration. E.g. I saw material in the material column and then again in the last column that should have shown the combination of types. So in 15.1.7 you need to test whether this column here is static and works independent of the column setting in the registration.

**Comment by urapadmin** [comment]
but that will be in 15.1.7 and that won't roll out tonight because I am kinda tired.

**Comment by luizaogs** [comment]
Oh you meant that those should appear in the heading, I see. Ok.

Go to sleep!

**Comment by urapadmin** [comment]
### recording 15.1.7
I am back online, sort-of. I am experiencing roll-out fatigue. However, the thing that needs testing here is really only that in the unit collected material list the last column should always show a combination of cm-type (bulk, small find, sample) and the small find for small finds INDEPENDENT of what is set to populate the third column of the collected material list in registration.
