### ISSUE TITLE
deleting a locus must delete the tags that tag it.

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2169]
I also think one should be able to delete a tag even if it still tags things. At least as an admin option.

This is coming out of #2166

**Comment by luizaogs** [comment]
This is the case in MKAP currently. There's a "phase I" tag that I just noticed when I was going in there to create an actual tag. We did not create and haven't used "phase I" and I assume this was something Laurel created during testing, but I now can't delete it because the locus that was presumably tagged with it has been deleted.

**Comment by urapadmin** [comment]
### recording 19.20
- tags get detached now from loci when the latter get deleted

**Comment by luizaogs** [comment]
Works.
