### ISSUE TITLE
github: Find a new bot to assign the creator of a ticket as assignee.

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2213]
the old bot does not work anymore

**Comment by PeterDeathBredon** [comment]
We are using actions-cool/issues-helper@v3 now to automatically add assignees on creating an issue.
documentation is here: [https://actions-cool.github.io/issues-helper/base](https://actions-cool.github.io/issues-helper/base).

I opened a feature request with them because I want to add the currently logged in user and a static user: [https://github.com/actions-cool/issues-helper/issues/160](https://github.com/actions-cool/issues-helper/issues/160)
