### ISSUE TITLE
Harris Matrix: Test the first attempt on AA

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2398]
We are testing currently if the HM generator spits out the correct layers and relations and if the visualization makes sense to you or where it is causing troubles (archaeological troubles, intuition troubles, whatever) and why.
Note that to achieve a view like this I have eliminated all transitive relations. So If there are three layers A,B,C with the physical relations A->B, B->C and A->C, the relation A->C is redundant for the chronology and so I remove it. Please report if that causes troubles working with the matrix. Only if we know the troubles we can actually think of ways to deal with them.

Here is AA. The left visualization is my very first attempt of drawing the thing myself. That has issues I will try to overcome (particularly the overlapping horizontal lines) but I think it already has some small advantages over the out-of-the-shelve DAG visualization on the right. But that one shows you exactly from where to where the chronological relation runs. Note that in this visualization the arrows are not only coming in from the top but also from the sides (and that is one of the things I really don't like about it). It all means the same: A relation runs from the tail to the arrow head. 

![grafik](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/b593a044-adf9-49a7-9d45-74f99283be44)

**Comment by luizaogs** [comment]
Ooo cool! I will compare it to the database at some point today and get back to you.

**Comment by lbestock** [comment]
@urapadmin Are you sure you have your left and right here correctly? The graphics then are opposite from the ones you gave me for URAP and will make my head spin.

**Comment by luizaogs** [comment]
Oh I was just about to look at this. So should I wait?

**Comment by lbestock** [comment]
You can look and compare them but in your notes call them "the one with square loci" and "the one with oval loci" or some such so that you can disentangle.

**Comment by urapadmin** [comment]
I don't understand. The two look identical to me (and honestly, they must be identical because all I do is draw the lines differently). 
If what you mean is that your FA (which this ticket is not about) is different from the FA I send you last time. Yes, because you changed the relations.

**Comment by urapadmin** [comment]
Or is this about the fact that the oval ones are right and the rectangular ones are left? Why is that a problem? They show the same thing slightly differently and all I need to know is if it is correct. I do not care if it is correct or incorrect in the oval or the rectangular part. If it is incorrect in one, it will be in the other, too.

**Comment by lbestock** [comment]
But how will you know which one we are referring to? (Yes, that was what this was about. I try to stick to the actual ticket...)

**Comment by lbestock** [comment]
Deictics are dangerous.

**Comment by urapadmin** [comment]
They are identical. It does not matter.

**Comment by luizaogs** [comment]
Wait. So yours IS the one on the left? Just asking because if something is unclear I expect that that only matters if it's the one on the left so that you can change it. 

(I assume you didn't want to close the ticket...)

**Comment by urapadmin** [comment]
no,no,no. Okay, this was too complicated. 

Guys, just focus on the right one, the one with the elliptical loci and stray arrows. Forget about the one on the left. And just test if the result is correct.

**Comment by urapadmin** [comment]
and no, I really did not want to close this. Apparently that happens on ctrl+Return.

**Comment by luizaogs** [comment]
Is there a reason why AA-025 is off to the side? That confused me, despite the arrows.

**Comment by urapadmin** [comment]
Why the layouter placed it to the right in this case is not clear to me, either. The positioning of the nodes is the part I leave to an off-the-shelf layouter (because that is a really complicated algorithm and I have my limits). But if I render it with less space between the loci it stops doing that:

![grafik](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/1e628a17-a179-43a7-a1c5-41f6bfe7fccd)

I just had the feeling that the more condensed version is actually harder to read.

**Comment by luizaogs** [comment]
The transitive relations do not bother me if all I'm looking for is chronological information. I guess that is primarily what this would be for and it does certainly help with visualization, since otherwise we would get so many more arrows. BUT I wonder if it could lead to confusion? Not sure what could be done to make it better, however.

**Comment by luizaogs** [comment]
And oh yeah, no. I think I would go blind trying to figure that condensed one out.

**Comment by luizaogs** [comment]
Besides the transitive relations comment, I believe the AA relations are rendered correctly here.

**Comment by luizaogs** [comment]
Hm though actually, some of the things on the same level are probably not contemporaneous. AA-022 is likely late than AA-024, for example, even if there is no direct relationship between the two.

**Comment by urapadmin** [comment]
so, where do we stand in AA?
- do think the algorithm has inferred the chronological order correctly as far as the records allowed it?

- Are there any locus relations you want to add (not interpretational relations, real one that were wrong or missing) or have added to the recording database?

- Which "interpretational relations" would you want to add (don't add them to the database)? 

I would render a new version that highlights the interpretational relations and perhaps the positive contemporaneous relations (in contrast to the "accidental" chronological positions). Then we can think about the use of that when we see it.

**Comment by luizaogs** [comment]
As far as I could tell yesterday it rendered things correctly (besides the uncertainties above) but I will check again in a bit and give you the interpretational ones, too.

**Comment by urapadmin** [comment]
no rush! 🐌

**Comment by luizaogs** [comment]
Woops, I see a potential problem in the FA thread -- does that affect this too?

**Comment by urapadmin** [comment]
no, I can at least already say that the missing relationship was unknown to my renderer at the time when I made the graph.

**Comment by luizaogs** [comment]
Ok, the algorithm has rendered AA correctly based on the available chronological information in recorded relations. I do not need to add relations to the recording. But:

- I am still iffy on whether the lack of transitive relations affects my interpretation of the HM. Certainly not when I am looking only for chronological information -- that's fine -- but I wonder if it could lead to misunderstandings of the stratigraphy itself.  I don't want more arrows in there, that would be messy, but I wonder if there is a way to note that those relations exist in the HM. Though @lbestock does not seem to have been bothered by it so maybe it's just a Luiza problem. (My confusion becomes clear with AA-008 and AA-013, for instance. AA-008 is the top layer of the fill of AA-013 but in the HM it does not look like they are directly related, because AA-008 is on top of lower fill AA-014, and that is the one rendered directly above AA-013. Which is correct - just confusing.)

- The loci rendered on the same level are giving me some trouble. Some because I want to add interpretational relations (see below) and others because there is no way to know if they should be considered contemporary but the HM makes it seem like they are. So AA-010, AA-008, and AA-009, for instance. Leaving them on the same level seems like the only real option since I do not know if one should be higher than the other, but then I want a way to mark that on the HM. Same for AA-014 and AA-011. And AA-013, AA-012, and AA-016. And AA-018 and AA-021. And AA-023 and AA-015. AA-017 and AA-020 are likely indeed on the same level, but whether AA-025 should also be thought of on the same level is not clear.

- AA-024 and AA-023 -- they are joined walls but they are so badly preserved that we could not tell which was built first, which means that there is no chronological relationship noted in the locus relations. BUT the HM makes it seem like AA-024 is later, which is problematic. If anything, I suppose they should be on the same level. This is also a problem for having AA-022 and AA-024 on the same level, if we do not know what the relationship between AA-024 and AA-023 is.

- Interpretational relations I would add: 
AA-021 is later than AA-024 (rather than on the same level, as rendered here)
AA-022 is later than AA-024 (rather than on the same level, as rendered here)

**Comment by urapadmin** [comment]
As for the AA-024 issue: In that case I would also add an interpretative relation AA-024 <-> AA-023 as contemporaneous or even make them a cluster (see #2399) That lifts them safely on the same level.

**Comment by luizaogs** [comment]
Sure, that works.

**Comment by urapadmin** [comment]
alright. I close these and work on solutions. We open new tickets when I have something to show. Thanks for testing.

**Comment by luizaogs** [comment]
👻
