### ISSUE TITLE
Recording App: deleting a locus relation deleted two

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2400]
Scary because I am in real data.
Testing HMs for URAP.
I caught a double relationship: FA-016 was both above and sealing FA-024. 
I deleted the "seals" relationship.
This also deleted the "above" relationship.
Very scary!

By chance I have this open on two different devices at the same time, so I can give screen shots of both.
This is what it looked like:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/ee842926-1754-4b27-bdfe-6ff49d48a2f1)
I hit ONE DELETE button and accepted the "do you want to delete this relation?" popup.
And TWO relations disappeared:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/57661284-c4bb-4809-9822-d7a7c7f6c16e)

I am not so sure this is a real problem, because it is no longer possible (was it ever?) to have two relations between the same two loci. I will now recreate the "above" relationship because I want that in there.

**Comment by urapadmin** [comment]
yes, I am really surprised. It is not and should not be possible to create two different relations between two loci. No idea how that happened. But URAP is old and there were times when that was buggy, of course. 
I will look into the deletion but, honestly, I suspect I delete the relationship between two loci, assuming that there can only be one. In the background I also have to delete the opposites. so check on that opposite locus, too!

**Comment by lbestock** [comment]
It deleted both of the opposites (both were there) and then performed as I expected when I (re)made the one proper one. Created the opposite.

**Comment by urapadmin** [comment]
Okay. I'll look into it in the next FileMaker phase.

**Comment by urapadmin** [comment]
Apart from the fact that URAP data comes from a time where relationships would not have been checked like today, I do remember now that for a short time it was even possible to have two different relationsships between two loci. There was an esoteric argument for a very special case where that was possible. I never understood it and can't remember the exact case.
Afterwards I limited it to one relation between two loci because it got too complicated down the line.

Currently according to the code and according to my tests there cannot be two relations between the same loci and it is correct that if there were, they both would be deleted when one of them gets deleted. That is one of the reasons why it isn't allowed to have them in the first place.

I am inclined to close this and implement a check and warning in Kiosk for this rare case.

**Comment by urapadmin** [comment]
see - #2716
