### ISSUE TITLE
kiosk/recording app: add more than one supervisor for a unit

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2415]
I am trying to import Abydos excavation data into kiosk. There are multiple excavators who oversee a unit. It would be great to have the option to add two or more supervisors to a unit. If there is an add button next to the supervisor field that would be great.

**Comment by urapadmin** [comment]
adding @lbestock and @luizaogs here as it is a general question for a feature. 
On unit level I can imagine that it makes sense for some projects to have an option to add all the team members involved in a unit and their roles in the unit. What do you think? In Egypt the Reis might have to be mentioned, the ceramicist etc.

**Comment by luizaogs** [comment]
Yes, that makes sense to me.

**Comment by urapadmin** [comment]
I would wish to postpone this. If I implement this the Kiosk data structure changes and that would cut MADP off of future updates of the recording app while they are in the field.

**Comment by urapadmin** [comment]
so question is: How important is this feature for BUAP right now?

**Comment by lbestock** [comment]
This is not super critical. We can input data for BUAP without this now and because it's really only at the unit level and we are not making hundreds of units it's possible to keep track of what needs to be added later.

I also note that the point about adding the Reis is pretty great. (Not just because I am missing Reis Ibrahim.) One of the significant criticisms of past archaeology is that by focusing on the person who makes the notes, all the other people who played roles are written out of the record, and that often includes ignoring real contributions to the decision making. So at Abydos in fact I wish it would always be the case that we would be able to record not just supervisors but Guftis for each unit. When I was very green myself and still learning Abydos, the units I dug when Ahmed was the Gufti sucked in comparison to those when I was working with Ashraf. Because Ahmed was a crappy archaeologist and a jerk, and Ashraf wasn't and could lead a team of workmen. That is archaeologically relevant information just as much as that I was a good archaeologist in comparison to some of the other supervisors in my cohort.

**Comment by luizaogs** [comment]
If you guys really need something before I get back, that’s ok - the updates I’ve been requesting are quite helpful but they’re also not strictly necessary and I can work without them if need be.

**Comment by lbestock** [comment]
You are in the field! Getting new data AND simultaneously making valuable contributions for the software. This data has been sitting in my office for 10 years. You get priority. Also it won't slow BUAP down more than a nanosecond.

**Comment by urapadmin** [comment]
### recording app 15.10
- there is now a valuelist "valuelist_team_roles" where the available roles that a team member can have in relation to an archaeological record (currently units but I have designed this so that it can be used e.g. for collected materials, too).
- unit has a new box that simply lists the currently involved team members and their roles
- with a button you activate a new layout where you can add a new team member to the unit and specify a role and if you wish dates and a note
- the team member can be selected from a list or you can type in whatever you want. That allows you to add somebody who appears only in this unit and does not need to be added as a team member
- test if these new records sync properly

**Comment by luizaogs** [comment]
If I add someone who is not part of the team members list, that person does not appear in the list at the unit level, even though I can see them in the menu where I add the roles: 

<img width="357" alt="Screenshot 2023-12-30 at 9 54 49 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/1f93c939-3f36-44bb-a771-98884eb60e9b">

<img width="814" alt="Screenshot 2023-12-30 at 9 55 02 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/d7d56a02-6bb9-4e12-81dd-57229241e0f8">

Ah wait, not entirely correct. He now shows up after I added dates, but he had not when I had just added a note: 

<img width="360" alt="Screenshot 2023-12-30 at 9 55 54 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/6bc77277-d0e9-4e87-a391-e5f6e278b579">

**Comment by luizaogs** [comment]
The rest is ok, including synchronization. (Also see #2451 )

**Comment by luizaogs** [comment]
Ah wait, also: should the header say "role in xyz"? Or is that supposed to have the unit identifier?

**Comment by urapadmin** [comment]
> Ah wait, also: should the header say "role in xyz"? Or is that supposed to have the unit identifier?

no, that was me thinking "Oh, I must remember to change that into a real identifier" at some point and then, you know, age, ...

**Comment by urapadmin** [comment]
### recording 15.11.1
- down to just "role" as label for the role field. "acting as" would be my alternative as this mustn't be the general role of that team member but the one in this case. But "acting as" sounded a bit denigrating of people's beloved titles in my second language understanding.
- not team members should show correctly now

**Comment by luizaogs** [comment]
Looks good now.
