### ISSUE TITLE
Kiosk/Recording: Can't Enter Any Data for Record Details for Deposit

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2417]
I was trying to record locus type and then trying to fill in "record details for Deposit". After entering that tab, I can't seem to click on any drop down and it is also not allowing me to type anything in the text fields. 

I am on macos 13.5.2 and filemaker 19.4.2.204.

**Comment by urapadmin** [comment]
that happens when one stitches together a server in 2 hours.
This is due to a configuration mistake: In the admin tab under "locus types" the configuration must look like this:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/f2faeb41-cf99-4178-a368-9c471bb55ae5)
For some reason I seem to have forgotten to select the correct values for "additional field set"

**Comment by urapadmin** [comment]
woops and there is also a type in the "layout for details" for "bu". Must be "locus_type_bu".

**Comment by urapadmin** [comment]
I should have added that this is a task for an admin who has some experience with configuration issues. I was hoping that @lbestock is still with you :o) Otherwise let me know and I'll fix this myself.

**Comment by lbestock** [comment]
We are all still together! But not much longer. And these guys are MUCH faster than I had expected so I have some catching up to do.

I will hit the various points of configuration we discovered needing attention this afternoon and let everyone know when we're good to add more data.

**Comment by urapadmin** [comment]
@lbestock Have you attended to this?

**Comment by lbestock** [comment]
I have!
