### ISSUE TITLE
recording app: ability to input NEFs in image containers in FM

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2423]
Inputting legacy data from BUAP.

I am to the stage of wanting to put images into the dayplans and loci. It is BY FAR easier for me to do this in the recording itself than by any of the methods of assigning context through the File Import. But the DSLR photos are all NEFs and Filemaker will not allow me to put a NEF in an image container. Is that something you can control, @urapadmin ?

**Comment by urapadmin** [comment]
have you tried putting a NEF as a file into the image container (in the end the image container is a file container, that's why you can attach an audi file)? I am not sure what will happen but it could be that Kiosk imports those NEFs correctly. And next time you export a new FM database you'd see a proper image (the NEF would have been thumbnailed by Kiosk). 

What I cannot do is make FileMaker acutally show the NEF as an image when you put it in.

**Comment by lbestock** [comment]
What I tried was clicking on the image container, saying "insert image", and navigating to my NEFs. They were all grey. Let me try via insert file.

**Comment by urapadmin** [comment]
did this work?

**Comment by lbestock** [comment]
Yes.

**Comment by urapadmin** [comment]
this might be worth a paragraph in the user's manual (the one for all users)
