### ISSUE TITLE
recording app: request ability to format text with italics, underlining, and bold

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2447]
I have no idea if this is remotely possible, and given that FM is a constant headache I'm not even sure it should be implemented if it could, but I'm wanting it.

Inputting legacy records from BUAP we lose some information that we could keep if there were text formatting options. Underlining is frequent in the notebooks. I also long for the ability to italicize things - there is a ton of Arabic written in roman script sprinkled in the notebooks and it's not always recognizable as such, for instance when words are spelled the same as a word in English. I shudder to think of future encounters with "bus coffins" in the recording.

**Comment by urapadmin** [comment]
theoretically it is possible in FileMaker (that would be a real headache in the browser as it needs an editor). BUT underlining, italicizing and such things are not data. They are half layout half semantic. I highly recommend against it because it enriches what was pure data with formatting commands that have to be filtered out all the time in the future when it comes to searching, querying etc. Remember the WYSIWYG editor in the wiki? The problematic behaviour of that thing was in part because layout instructions are problematic. HTML has a long history that teaches us how problematic mixing up layout and semantics is.

**Comment by urapadmin** [comment]
won't happen in FileMaker and presumably also not in a future text. Buys too many problems and is from my point of view semantically as sound as using three quotation marks. But the latter is just my opinion. The problems are a fact
