### ISSUE TITLE
recording app: Locus name change?

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2448]
I am not sure if I can do this. I tried in the app and I read the documentation but I couldn't find it. 
I created a locus (i.e. 18) and then I need to change it to Locus 18a. But the app won't let me edit the locus name once I created it. Also, I cannot delete a locus.

**Comment by urapadmin** [comment]
you can do this. We have made this as hard as possible because in the field changing the name of a locus is often not a good idea and needs awareness. 
I can't remember, but I think you have to be logged in as admin in this case. Then you go into the locus and switch on what we call "temporary free input", which is a little button in the burger menu. once you do that a new button appears in the burger menu. That one allows you to change the identifier. 

Does that help?

**Comment by maychu16** [comment]
Yes. Thank you. but I don't know how to log in as Admin.

**Comment by urapadmin** [comment]
oh, I didn't know that. Just restart and then it is user admin, password admin.
Just make sure to log out and back in as yourself after you renamed your locus.

**Comment by urapadmin** [comment]
can we close this?

**Comment by maychu16** [comment]
Yes, I will close it now. I could rename the locus.
