### ISSUE TITLE
ANC import corrections

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2486]
We are finding errors in the ANC FM database after seeing what was not imported. Those will have to be corrected by @urapadmin in order to be brought in with a synchronization (or @maychu16 can update the ANC FM? Plan/person of attack can be up in the air, but we need this ticket to keep track of the errors we find).
37086: marked as lot 51, should be lot 37
37094: marked as lot 30, should be 38
37180: marked as 48, should be 43
37176: marked as locus 39, should be 30
43451-43457: all marked as locus 40 lot 1, should be lot 62
37387: marked as locus 16, should be locus 15
39401: marked as lot 70, should be 71
38043: marked as locus 15, should be locus 15b (ouch, ouch)
38206: marked as locus 68, should be locus 69
40920: marked as locus 57, should be locus 51

This is the list of things that will change in the ANC FM database.
The remaining red things in the locus_no_lot list will bechanged in Kiosk.

**Comment by lbestock** [comment]
Strategy decided: @lbestock and @maychu16 finish the spreadsheet of things that were not imported, @maychu16 makes corrections in the ANC database in the BUAP shared folder and/or recording app so that there are no longer discrepancies between the ANC database and the recording, and tells @urapadmin when done so he can update. Then the synchronization should bring in the previously missing ANCs.

**Comment by lbestock** [comment]
These two things are done.

**Comment by urapadmin** [comment]
I moved the changes from the ancdb to Beset, so as soon as May has updated those lots/loci things should fall into place.

**Comment by maychu16** [comment]
Could you please check if you changed 38043 from Locus 15 to Locus 15b? It has not yet been inputted into collected material.

**Comment by lbestock** [comment]
I did make that change in the FM ANC database and it seems not to have translated to the Excel export. That "b" is a problem, @urapadmin?

**Comment by maychu16** [comment]
All other ANC numbers in Locus_no_lot has been inputted and there should be no more (except for 38043) from Op 171, 172, 174 and 175 if the same query is run again.

**Comment by urapadmin** [comment]
I have 15b still in the FM database that I used yesterday.

**Comment by urapadmin** [comment]
and so it is on the google drive

**Comment by urapadmin** [comment]
ah. Got it. It has to be 15b. Well that is a problem, indeed.

**Comment by urapadmin** [comment]
Looked at it. While I could have found a way to import the locus as a text turning the loci into a text in the original Abydos database reveals quite a number of new issues: Sometimes a locus "1" would have been typed as "1" and sometimes as "01". Now that we are importing this as a text these would be two different loci. So that is not a good idea. 
You guys must solve that by renaming this locus and then typing the one collected material in manually, too.

**Comment by urapadmin** [comment]
wait, perhaps I can manipulate the excel sheet manually...

**Comment by urapadmin** [comment]
yes, that worked. 38043 has been imported as a collected material now.

**Comment by urapadmin** [comment]
done. You find a new "locus_no_lot 2.xlsx" in the google drive. It still has a few records.

**Comment by maychu16** [comment]
locus_no_lot_2 came up with two new ANC numbers that I need to create a lot for. I am wondering if you changed any query rule for the second sheet? Because these two weren't in the first one. Then, I wonder if there are some ANC numbers that were not imported (although they should be) but doesn't show up in the query results etc.

**Comment by maychu16** [comment]
Although I created a lot for these two ANC numbers and synced it, it does not seem like they got imported.

<img width="1508" alt="Screenshot 2024-01-20 at 9 47 58 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/ca6c95fd-1305-4356-a888-901122bab93f">

**Comment by urapadmin** [comment]
which were those two?

**Comment by maychu16** [comment]
38055 and 38062 from Op 175 Locus 22 Lot 37.

**Comment by urapadmin** [comment]
I'll look into it. Tomorrow 💤

**Comment by urapadmin** [comment]
okay, the reason why they were not imported was that they had been already imported before. Both 38055 and 38062 exist.
Now I have to find out why they were listed in the locus_not_lot_2 spreadsheet.

**Comment by urapadmin** [comment]
unclear. When I ran the locus_no_lot query again, those two were not on the list any longer. I won't be able to find out what happened in this case. Let's wait if similar issues appear again.

**Comment by maychu16** [comment]
Umm that’s weird that they were imported before. Because I only created the lot yesterday after it showed up on the excel sheet.

**Comment by urapadmin** [comment]
yes, it is. But you were also on somewhat older data for a while yesterday (or that was at least my feeling) and we had imported stuff in the background while your device was in the field. So there were many things going on at once that make it pretty hard to find out about this case. 

That's why I think we just shrug in this instance and wait what the next rounds bring.

**Comment by urapadmin** [comment]
closed due to inactivity
