### ISSUE TITLE
kiosk: reset recording group not working?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2508]
Huh. Is this not working or am I just doing it wrong? Tried to reset the recording group as per your email and got the following error, though all of them are just in the "synchronized - needs prep" stage. 

<img width="1512" alt="Screenshot 2024-01-25 at 8 50 57 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/36340b38-a8a1-4427-8478-2e965d5722c0">

**Comment by urapadmin** [comment]
was that resetting all workstations or resetting the recording group (for strange reasons an option on a dock)

**Comment by luizaogs** [comment]
Ah, resetting all workstations. The option in the menu, not the individual dock menus.

**Comment by urapadmin** [comment]
then the message makes sense

**Comment by luizaogs** [comment]
Hmpf. Does it make sense to move the reset recording group to the menu? It didn't even cross my mind to look in the workstation menu.

**Comment by luizaogs** [comment]
Ok, I'll run the reset recording group then.

**Comment by urapadmin** [comment]
> Hmpf. Does it make sense to move the reset recording group to the menu? It didn't even cross my mind to look in the workstation menu.

That's where you should think it belongs. But that would not work because there can be several recording groups. And options in the menu are independent. What is missing here is a menu for the recording groups themselves (as long as you have only one you can't even see it): #1021 One of those numerous loose ends ... But it has a ticket.

**Comment by luizaogs** [comment]
Ha ok.
