### ISSUE TITLE
Kiosk kiosk at ASOR

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2562]
Just bringing it up now because the call for papers came out recently, so before I forget. I am planning to go but it's in Boston, so @lbestock you might be able to go as well (since I don't think it would make sense to have me manning the table alone). Maybe something to keep in mind if ARCE goes well.

**Comment by lbestock** [comment]
100% 
I've been invited to give a paper as part of a session on violence in Africa so I should be there anyway! Bigger stage: we should think about AIA in January, too.

**Comment by luizaogs** [comment]
Ah well I was going to try to persuade you to present invisibility in the ANE art panel but if you got invited that's even better :)

**Comment by lbestock** [comment]
Paper accepted. So this will happen. With to-scale bookmarks.

**Comment by lbestock** [comment]
Conference is November 20–23 at the Hilton Boston Park Plaza. And they want powerpoints November 6th? Are they crazy? That is so early, and also the day after the election.

**Comment by lbestock** [comment]
And while the 2024 exhibitor prospectus doesn't seem to be live yet, it looks like in 2023 it was much like ARCE. $425 for just a table, $1000 gets us the table and some additional stuff including advertisement (and we could even get the logo on the tote bag. The tote bag that they advertise as being environmentally friendly because it is reusable. This is the world we live in, where trash no one really needs but that might take a bit longer to throw away than a plastic bag is how we tell ourselves we save the environment.)

**Comment by luizaogs** [comment]
Yeah I haven't heard anything (even though I was invited to speak, too) so you might be manning this by yourselves. On a day when my students are getting arrested and I can hear helicopters from my house, I really didn't need this as well. Great.

**Comment by luizaogs** [comment]
Well that’s one crisis averted, ASOR is just incompetent.

**Comment by lbestock** [comment]
Or session chairs just reviewed things at slightly different times, or it just takes a few hours even to send a bunch of auto generated emails. I wasn't worried :) But am glad for your sake that now you have the positive confirmation.

**Comment by luizaogs** [comment]
How rational of you.

**Comment by luizaogs** [comment]
If you want to do more than just the exhibit table, there's also this: https://www.asor.org/am/2024/round-tables-2024?_zs=7d5gM1&_zl=PVFT7

**Comment by luizaogs** [comment]
And the exhibitor stuff for 2024 is out: https://www.asor.org/am/2024/exhibit-sponsor-advertise-2024

**Comment by luizaogs** [comment]
This is cheaper if booked by August 1st.

**Comment by lbestock** [comment]
I have written to Andrew and Sarah to request that the Institute sponsor part or all of it.

**Comment by luizaogs** [comment]
And last reminder for this, too.

**Comment by lbestock** [comment]
I have an agreement from the Institute to split the cost on this, and have filled in the paperwork. Payment will be done tomorrow.

**Comment by lbestock** [comment]
All set. One exhibit table set up in a place with electricity and room for the projector. One half-page ad in the digital welcome packet. One destination QR code for the scavenger hunt activity (painful, but funny, and didn't require more money).

**Comment by urapadmin** [comment]
> One destination QR code for the scavenger hunt activity (painful, but funny, and didn't require more money).

THE W H A T?

**Comment by lbestock** [comment]
![image](https://github.com/user-attachments/assets/8c977251-bf30-46f9-b764-ea14ae526466)

**Comment by urapadmin** [comment]
this is ridiculous

**Comment by lbestock** [comment]
Reopening this because there are things to do to get ready.

- [ ] make hand balm
- [x] before October 15 sign up for a [roundtable](https://www.asor.org/am/2024/round-tables-2024?_zs=d60TR1&_zl=VxQa7) - thanks to Robyn Price for the suggestion
- [ ] get the other printer to make to-scale north arrows

**Comment by urapadmin** [comment]
it's not reopened. I reopen it.

**Comment by luizaogs** [comment]
Roundtable proposal submitted. 

Kiosk: digital field recording for archaeology

Do you have a field project? Are you looking for a more efficient way to gather your data and analyze it for publication?

Digital recording is relatively common in archaeology, but it has faced hurdles to widespread adoption, particularly by academic archaeologists. These hurdles are not only or even primarily technical, but rather range from the theoretical, to the physical and the administrative. This roundtable will introduce Kiosk, a free and open-source integrated iPad recording platform and browser-based data manager for field archaeology that solves many of the issues common to other digital recording options. The roundtable’s goals are to allow project directors and others interested in digital recording to ask questions about the software, try out many of its features, and suggest additions that would facilitate their work in the field.

Kiosk is used in the recording of excavation and survey data in projects from Egypt to Peru and Cyprus. It allows for the recording and integration of data in the field, from field journals and photographs, to context information and the automatic rendering of Harris Matrices, to object registration. Kiosk also enables the analysis of data for publication by allowing users to easily query and search through their data online post-season. Kiosk is available to anyone who wishes to use it, including tech support for customization and while in the field. It is suitable for everything from a one-summer project run by a graduate student, to a field school, to ongoing excavations with decades of data to digitize.

**Comment by luizaogs** [comment]
(I forgot to mention that I signed up for the roundtable with your email, Laurel, and since the deadline is tomorrow you might get emails soon. So just letting you know.)

**Comment by lbestock** [comment]
We got approved! @luizaogs I'll forward you the email so you can share the signup link.

**Comment by luizaogs** [comment]
Do you want it shared anywhere specific?

**Comment by lbestock** [comment]
I had an idea in the middle of the night, sleepless with election anxiety. I will email all the projects currently using Kiosk who work in the eastern Med/overlap with ASOR. I'll ask them for a slide for our loop, and also give them that link and tell them that if they have any friends or colleagues who are digging (especially starting a new project, as that seems to be our strongest market) who will be at ASOR and might want to learn more, spread the link. But otherwise if you don't have anyone specifically in mind, don't worry too much about it. I think ASOR themselves will be promoting the roundtables. I also just noted that it's my first conflict for the conference. I was supposed to be in a board meeting then for AmSARC. Roundtable wins.
