### ISSUE TITLE
hm: remove excess relations

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2572]
- Whoever recorded this (see #2402) must have been bitten by a goat: 
CA-002 is not only sealed by CA-001, it is also "adjacent to" and vice versa. And that's where the system gets confused.

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/2402#issuecomment-1984318259_

- Once and for all: Since nobody has ever given me a really conclusive reason why two nodes can possibly have two relations to each other, I will now officially drop that possibility until somebody actually has a valid example in the field. @lbestock: Only so that you know.

**Comment by urapadmin** [comment]
### plugin 0.13
This gets more and more problematic and I am loosing a lot of time wrestling with multiple recording issues, some of which cannot really happen anymore with our current version of the recording system. This is now how it is:
- duplicate relations with chronological impact are removed from the graph but shown in the error panel under "relations, dropped for other reasons". They need to be separate from the cyclic / contradictory relations for current technical reasons.
- relations dropped due to missing chronological information appear in the same part of the error panel

**Comment by urapadmin** [comment]
FA needs a fresh look now that we have this error type: It seems to have excess relations, too.

**Comment by luizaogs** [comment]
This looks fine in terms of icons, but I leave it open for @lbestock to look at FA.

**Comment by lbestock** [comment]
I am very late to this party and only trying to wrap my head around it now.

@urapadmin I have noted that you do not allow two relations between the same loci and I have read my Harris and I accept this.

Why do some units have an error sign in the menu so that I can toggle the error pane on and off (CC) and other units simply have the error pane visible and I can't turn it off (FA, FI, CA)? CC only has relations removed for other reasons, not cyclic ones, but it still should be possible to toggle the pane off, right?

This probably already has a ticket but post-testing there should be a key so the error icons can be easily understood.

Now for FA...

**Comment by luizaogs** [comment]
There is a ticket for the error panel issue, I believe, but not for a key (which would indeed be helpful). I think if we create a key ticket this one can be closed?
