### ISSUE TITLE
Ad for ARCE abstract booklet

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2621]

**Comment by urapadmin** [comment]
my first drafts are on the google drive under presentations/arce booklet ...

**Comment by luizaogs** [comment]
You guys get a full page? 

I don't think the Mars one is super recognizable as Mars so I personally wouldn't use that one. And between the first two, I like the taglines on the second one better.

**Comment by urapadmin** [comment]
I don't know what we get. In the 2023 booklet I cannot see half pages. Everybody who has an ad seems to have a whole page. And the Gold sponsorship in 2023 came with a full page. But currently I rather try to find a visual concept and way of communicating Kiosk's values at all.

**Comment by luizaogs** [comment]
You got the Gold? It looks like half.

<img width="957" alt="Screenshot 2024-03-30 at 12 11 06 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/ff94a4bc-be30-48fd-a66a-7630d1313f5d">

**Comment by urapadmin** [comment]
evidently they have changed that a lot this year.  Last year this would have been the much cheaper Silver except for the president's reception - well, I don't say how important I find this addition here in public.

**Comment by luizaogs** [comment]
Har har har.

**Comment by urapadmin** [comment]
well, I am lying. One already got that dinner as a gold member last year. I was confused. And it was already half a page. But it seems every exhibitor in 2023 had Platinum, as they all had a full page, unless I am blind again. Perhaps we go only with qr code and logo if it is just half a page.

**Comment by luizaogs** [comment]
That probably makes sense. Though maybe also a "Go Remote. Go Digital. Go Paperless" in there wouldn't hurt.

**Comment by urapadmin** [comment]
I would totally trade the reception for the other half page 👿

**Comment by luizaogs** [comment]
You should write to the very helpful ARCE person and tell them that.

**Comment by lbestock** [comment]
Ha ha I am just getting to this after a day swinging a pickaxe and reading a novel in the sun. And the first thing I notice looking at the abstract booklet from last year is a) Paul, and b) that Ramses II book! So I chuckle, even before I turn to the issues at hand...

**Comment by lbestock** [comment]
And next is that I can't believe that QR code works, and I note that the spider wears the amusing pullover :)
As for size - I wonder if it's just easier for them, since it's digital, to give everyone the same size. Now if Christina had ever answered in the multiple times I asked for the specs to design the ad, we might know. But I'm actually quite minded to give her a full page ad and just see what happens. If she comes back and says "no, you only get a half" then we can have something up our sleeve. But I would be more surprised at that than if it just went through, and then you know we could do the reception and the full-page.

**Comment by lbestock** [comment]
OK I am also now futzing. I agree the remote/digital/paperless is good. I think the image for remote was too much about remote and not enough about Kiosk and was hard to read as visually related, so I moved Oren over (still remote, just not as clearly so visually) and swapped out for another field image.

I had been thinking about more text. On the one hand, a lot of text would be in the way, and we all know I am prone to the long blocks of text in digital format that, um, do not work.

But it did strike me as worth mentioning that we have a table at the conference and have users from a variety of projects who are happy to give demos to potential users. And that the developer is there and happy to take questions and discuss customization and development of new features. The latter in part because it's a way of adversing that we HAVE a developer. But that might be better accomplished at the table itself? (Now I have a "the developer is IN" sign dancing in my head.)

I also found the HM not to read super well. I tried a different take on that.

**Comment by urapadmin** [comment]
NO TEXT!

**Comment by lbestock** [comment]
Got it :)

But be prepared for a "developer is IN" sign...

**Comment by lbestock** [comment]
What about the Brown logo and the Joukowksy Logo?

**Comment by urapadmin** [comment]
I like the extraterrestrial. Has some humour to it. 

Don't advertise the developer or he might not come. I also really see no reason to do that. All software has a developer and usually a few of them. That we have only one is rather a problem.

**Comment by lbestock** [comment]
Most recording systems have husbands, not developers...
I like Mars, too. I am just never sure how much my own humor (or love of hand balm) translates.

**Comment by urapadmin** [comment]
ja, that is an insider. Husbands don't make software you can try at the conference and is used by several projects. Otherwise they are developers. Really, let's drop that. 

The hint that Kiosk can be tried in the Atrium is better.

You also have other things to so, Laurel.

**Comment by lbestock** [comment]
Oh. Right. That.

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/fb72aa4e-6d03-4ab4-9801-da22ad30f073)

Done! And accepted vertical (so full page? I guess?)

**Comment by luizaogs** [comment]
I think you have a typo in exhibit?

**Comment by lbestock** [comment]
Ha ha! Then I sent them the wrong file, since I caught that yesterday. I will amend. Thank you :)

**Comment by lbestock** [comment]
Ha no, phew. I only put the wrong image here. The right one went to ARCE.

**Comment by luizaogs** [comment]
Ah good :)

**Comment by lbestock** [comment]
Wow it is really a google drive issue, yet again. The wrong one shouldn't even exist anymore. But I'm on a different computer than I was yesterday, and apparently it didn't synch.

**Comment by lbestock** [comment]
I updated it here because that would have bothered me for years.
