### ISSUE TITLE
Is it possible to add photos of sketches/sketches directly into the narrative box? 

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2796]
I am looking at excavation narratives that incorporate a lot of sketches. I think it might make a more natural flow if sketches and notes are in the same box since some excavators explain things with sketches. Right now, I put sketches in the day plan images area but this doesn't make as natural flow in reading these excavation notes. I am not sure if this is possible. Just an idea. 

Or insert these sketch photos as a hyperlink in the narrative text box so that people can be directed to these sketches instead of having to find them. This might be useful for excavators who like to sketch and explain things. But this is also more of a legacy data entry issue.

**Comment by lbestock** [comment]
Something that solves this problem exists! It was one of our major breakthroughs - the team from Sardinia wanted to have the ability to link images and narrative notes flexibly. Not in the same box necessarily (they wanted it particularly for photos) but it will solve the problem you encounter here, of needing to see the notes and the sketch that goes with them in the same place. It's definitely not just a legacy data issue at all. Only, I am having trouble finding where the feature is documented so that you can learn to use it. Give me a bit...

**Comment by maychu16** [comment]
Thank you. It would be great to learn how to use it. I read in the #1776 that it will show up with chain link. But I am finding that there are chainlink icons for some of the narratives even though I didn't use this feature. Is it somehow automatic?

**Comment by lbestock** [comment]
It isn't automatic. Can you put a screenshot of what you mean here? I'm in the midst of writing this feature into the users manual and then you will definitely be my guinea pig to see if the description/instructions are effective.

**Comment by maychu16** [comment]
It might just be because I am confused about what these three icons mean. 

<img width="186" alt="Screenshot 2024-08-18 at 1 38 37 AM" src="https://github.com/user-attachments/assets/b33fa9fe-7196-434d-a4d7-7090f6eb285b">

In the menu of the second icon, there are two photos with chainlinks beside them. They show up when I clicked on the little square (I don't know what this is called either) beside my 3 I 2011 narrative. Also those photos are for 2 I 2011. 

<img width="1512" alt="Screenshot 2024-08-18 at 1 38 21 AM" src="https://github.com/user-attachments/assets/c150e7ec-cdfa-400f-afcd-7f8730a9206a">

**Comment by lbestock** [comment]
Yup. Perfect you're in the right spot. The chain link in this case is what you hit to CREATE the link. The tab you're in is the calendar tab - should show you all dayplans from that day for that unit. I'm not quite sure why the date is a day off from the date of the narrative but that is an issue about date/time that I won't touch right now :) The leftmost tab is all dayplans from that unit at all, so you can see older ones. And then the right tab, the link one, is where you can see the images already linked. That is what should be empty until you create the links by clicking the link buttons in either of the other two tabs. (Note that you can also click on the image itself and see it larger next to your narrative.)

@urapadmin an idea to make this slightly more intuitive: once linked, the link button could change color. So that when one is in either of the left two tabs, one can see what has already been linked.

**Comment by maychu16** [comment]
Thank you. This is very clear now. 

 It continues to be a day off with 3 I 2011 photos showing up in 4 I 2011. I sort of think this is the same problem we had with time zone back then. The only photos showing up here are the ones uploaded to the server. Not the one I have inserted in the recording app. 

<img width="1512" alt="Screenshot 2024-08-18 at 1 52 22 AM" src="https://github.com/user-attachments/assets/245c7763-4364-43df-8e06-d3648bd07d3a">

Can I somehow see from the images tab that a particular image is linked to a particular narrative? or can I only see it when I click the square beside the narrative box?

**Comment by lbestock** [comment]
@maychu16 I have just written this into the manual. And then I sent you a link to comment on that, so you can see what I have written and tell me if it is useful to someone seeking this feature but not yet knowing about it before I upload the changes to the manual on the website.

**Comment by lbestock** [comment]
No way to see it when you are in either the trowel or calendar tabs - that was what I thought might be made easier with a color change to the link button suggested above. When you're not in the viewer at all, rather in the original tab where you can scroll through images and narratives and make them, there is no way to see what is linked to what.  

Can you see the photos you have just put in but not yet synchronized when you click on the trowel tab at least? All timezone related problems are on their way out (and then we are going to have a testing nightmare, so get ready....) So for right now I'm only concerned about you having a reasonable workflow. I'm really glad you're able to get back to this.

**Comment by maychu16** [comment]
Yes, the trowel tab shows all the photos: the ones I inserted and the ones from the server.

**Comment by lbestock** [comment]
Ok phew. Also phew for me: I found how we communicated this feature, which was in the video for new features 2023. Makes me feel less crazy.

**Comment by urapadmin** [comment]
do we have a video on this?

**Comment by lbestock** [comment]
Yes, it's in the New for 2023 part I, at 7 minutes.

**Comment by urapadmin** [comment]
and that's sufficient?

**Comment by lbestock** [comment]
The video that says "explained in a longer tutorial" that doesn't exist...
I think it would benefit from a longer (but five minutes max!) video. But also it needed to be documented in the manual, which had nothing about it, and that I have done.

**Comment by urapadmin** [comment]
Well, we leave those "user manual" tags everywhere but lack time and help to go ever list all the tagged issues and add them to the "manual".

**Comment by urapadmin** [comment]
- Can we close this? I have made the one request a ticket: #2800

**Comment by lbestock** [comment]
Yup, we even have feedback from May on the manual front. Which results in one more tiny request ticket...
