### ISSUE TITLE
github: links are wonky and want updating

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2830]
What happened in github? My bookmark for the testing page is kaputt. When I go to the office in githup and hit the link for testing, it is kaputt and I get a 404. Is it just the testing project has a new url for some reason? That seems probably simple. But bothersome: when I create an issue and try to assign assignees, I no longer see the list of people associated with the project. Is that only because there are now so many? They still pop up if I try to type something, but no longer just a list of everyone and I was disconcerted and miss the ease.

**Comment by urapadmin** [comment]
a) Possible that the links are different now because they changed stuff about projects (there are no repository-bound projects anymore). So those links simply need a new link.
b) I can see the users involved. But only if I am logged in properly. They are not visible to github users outside of our enterprise. So I am not sure where your issue is here.

**Comment by urapadmin** [comment]
I corrected the link on the office start page. But they are everywhere. Thanks GitHub! That at least was the most important one.
