### ISSUE TITLE
kiosk: potential problem with no default time zone?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2855]
Hm. I followed the instructions in your email, not selecting a timezone when creating a dock, but I expected to see one once the dock was created because you said to rely on defaults. Should I be seeing a timezone in my new Mac dock right now, or was I actually supposed to choose one? Won't mess with the dock further until you see this.

**Comment by urapadmin** [comment]
no, that's by design. You only see a time zone if it deviates from your default setting as a user.
My tentative design goal in general was to not bother users with anything about time zones unless their situation makes it necessary. If you leave your dock at the default it will operate according to your Browser's time zone (or if set, you user's explicit set time zones).

**Comment by urapadmin** [comment]
to be more precise: You only see a time zone mentioned in the Hub for a dock that has its time zone explicitly set on dock level.

**Comment by luizaogs** [comment]
Ah ok. Sorry, I saw that your dock had a timezone so was confused.
