### ISSUE TITLE
kiosk: q&v confusing error

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2861]
Sorry. I need a distraction and your release notification was a welcome email.

Tiny, but I see a weird error in PVD Q&V. Just for one query, the "how much pottery has been found in each ceramic category". There are no results, so I suspect that is why the error is showing up (because it only shows up for this one), but the error is wrong - Q&V is working just fine otherwise so the server is clearly not down, and I am clearly logged in. And the error shows up twice which is weird anyway.

<img width="1484" alt="Screenshot 2024-09-24 at 2 32 01 PM" src="https://github.com/user-attachments/assets/18884080-2214-4650-a515-cd796280fd5f">

**Comment by luizaogs** [comment]
Weirder: I had other queries opened earlier, along with this one, and then when I started closing them I got even more errors: 

<img width="1512" alt="Screenshot 2024-09-24 at 2 33 35 PM" src="https://github.com/user-attachments/assets/bb40775a-de71-4624-9147-f573728f998e">

**Comment by urapadmin** [comment]
a bunch of things here:
- that error message does not even help me. The actual error does not come through (once fixed it won't be less confusing for users but a more useful message for me)
- I suspect that PVD is not configured for su_ceramics. The issue here then is that there are queries installed for a project that can't handle them. That's more an organizational problem that we haven't had, yet. But before I tackle that I must make sure that PVD actually has no su_ceramics configured.
- the error message should not come twice or again. That's related to the particular query without input data

**Comment by urapadmin** [comment]
> But before I tackle that I must make sure that PVD actually has no su_ceramics configured.

yes, that is so.

**Comment by urapadmin** [comment]
okay, there was already a mechanism that I could have used to make sure that those queries only work with USTP (which is what we made them for): move them into a USTP sub folder under kiosk_queroes. I rolled them out for everybody.

- But doing that would also remove them from PASU, where they'd be useful as well. So I either duplicate them or I think one day of an attribute for queries that limits queries to certain projects by id: #2869

**Comment by urapadmin** [comment]
### Kiosk 1.6.4.3
- error message should only appear once
- error message should say something longer in brackets like here:
![image](https://github.com/user-attachments/assets/70ed89e5-143f-4636-ac37-eb5e2068f4d1) Just the error message would be a little different, mentioning su_ceramics or so. Nothing a user can understand but exactly what I would need to know what's going on.
- for now I leave the query in the PVD Kiosk so that the way Q&V deals with the error can be tested at all.

**Comment by luizaogs** [comment]
Need to wait for #2884

**Comment by luizaogs** [comment]
This query is no longer in PVD so I can't test this.

**Comment by urapadmin** [comment]
it should be back
