### ISSUE TITLE
kiosk/recording app: Is it possible to have photo linking for Loci description?

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2880]
I just ran into a locus sheet that has sketches in the description section. I know we have the option to link photos from day plan/ unit narrative with Op narrative. I am wondering if it would be useful to have the option to link photos to the description in Locus section. Would it even be useful?

**Comment by urapadmin** [comment]
Hi May! Good to see you around. 
Can you give me the example that made you have the idea?

**Comment by maychu16** [comment]
Thank you for the quick response! This is what I was looking at. 
<img width="570" alt="Screenshot 2024-10-03 at 10 49 54 PM" src="https://github.com/user-attachments/assets/facb4f34-043c-4e5c-9c52-6c2e1e19195d">

**Comment by urapadmin** [comment]
we'll think about it 👍

**Comment by urapadmin** [comment]
@lbestock
My first thoughts:
- slightly related to #2396
- instead of a list of interpretations we could have a list of texts with a type (interpretations / description) 
- once we have a list of texts we could theoretically have the same kind of narrative / image view that we have in the unit with dayplans and narratives

**Comment by lbestock** [comment]
But this isn't about interpretations, is it? It's about a locus description. And in fact it's on the line and I'm not totally sure I understand it - that looks like a section, not a plan, sketch. But what that end bit is? And 2m exposed this season is appropriate for a narrative - that's trench process, not intrinsic to the wall.

But interestingly - though with this one I would say @maychu16 it's not very critical and we'll have the photo of the locus sheet in there and since I can't entirely make sense of the drawing, even though I know the wall it refers to, I don't want to turn it into harder data than it is - the broader point is a cool one.

Currently, loci have ONE description and N images. So no way to link an image to a separate part of the description. I am very hesitant to have more than one text block in description of loci. The point there is that a locus is an intrinsic thing in the archaeology and has a static description. While it takes some time to fully expose a locus and know its description entirely, it shouldn't really change, just get more complete. If it changes, that's when you get a new locus. So process stuff I continue to want in narratives, where for good reason you can make new ones, and description specific to a locus should remain where it is and singular. So no linking to photos. In a case where an image is about a specific part of a locus or illustrates a particular point about that locus, that should go in the image description field itself, even if it makes it long. That's actually what I would do with the above example. 

But @urapadmin I see definitely why you jumped to interpretations. Because there we currently have only one, and we have long discussed having N for good reasons that are not only theoretically sound but relate to practice (I brought up the CC "house" problem in my intro class just Wednesday!) And in interpretations, we have no images. Should we? Should we have the interpretations tab look more like dayplan/narrative, with N images and N interpretations and the ability to link them? I kind of like that.

I do not want to muddy interpretation and description by having them in one place where you choose between them. I also taught Wednesday that it is both difficult and necessary to keep observation and interpretation separate. That's why they are separate tabs. I don't want description working its way into the interpretation tab, and I don't want interpretation getting out of its cage into anything else.

**Comment by urapadmin** [comment]
I don't want to put too much energy in defending this. But from my perspective interpretation never really belonged in the field recording app. And if then a single field should be enough for the in-the-trench interpretation. It's kind of the same argument you make about description. The one advantage of putting interpretation and description in one list of several text blocks and "flagging" them interpretation or observation is that you can change that flag. If somebody adds too much interpretation in the description you just flag it interpretation. Perhaps one should give up on interpretation vs. description altogether and use flags (tags, labels, whatever you call them) to mark things "interpretational". If all text blocks are in a list it is also easier to just cut out a bit of one text and move it into a new one that you then mark "interpretational" or so.
Different workflow. I just think it is often enough too hard to draw a really hard line between text that is supposed to be ONLY observation and text that is supposed to be ONLY description, even if that's what you would want to strive for. We don't disagree on the theory, I just don't know if we are actually encouraging a different thinking with the hard separation. We might as well encourage ignorance because we set too high a bar.

Using the description field of images is not solving the interpretation/description gap. It just moves the question to yet another place.

If you want to put longer things in image descriptions you will potentially cause layout space issues. Just be aware of that. It is also not very convenient, currently, to write more than a line into those fields in the recording app. That could be improved, though.

**Comment by urapadmin** [comment]
last thought on this: Starting with the second text block the default flag could be "interpretation" instead of "observation" or even a question "Is this interpretational?" that forces users to think about the distinction.

**Comment by urapadmin** [comment]
we thought about it and the gist is: As long as the recording app stays in FileMaker we leave things as they are. Interpretation does not even really belong in the recording app and is just a provisional field until that's done properly in Kiosk. So mingling interpretational text blocks with description text blocks is not on right now. Once we are in a future app referencing images from within texts will be a topic anyhow.
But in that future app we think we will be having a list of texts instead of two simple separate fields as I describe above. And then text blocks could be tagged as "interpretional" and texts will be able to reference certain images anyhow.  

@maychu16 For now Laurel's advice is the way to go: 
> In a case where an image is about a specific part of a locus or illustrates a particular point about that locus, that should go in the image description field itself, even if it makes it long. That's actually what I would do with the above example.

Should the limitation to one line of description below the photo is starting to annoy you, let me know. That can easily be improved.
