### ISSUE TITLE
kiosk: modified file does not have tz in file edit dialog

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2887]
Image f8887661-aa3a-4d8c-a597-c7c8c8c95ebd. If you look at it in the director's view or in FM itself you would see that I modified its description around 2:50pm today (LA time). The file edit dialog, however, does not show the timezone next to modified for this image. In fact, the "modified" date and time for it is wrong too, since it should be today.

The timezone shows up properly in the file edit dialog for the images I actually added, rather than modified, today.

<img width="1425" alt="Screenshot 2024-10-06 at 3 07 22 PM" src="https://github.com/user-attachments/assets/00afb278-6443-4495-98d0-a9a5db69a2f4">

**Comment by luizaogs** [comment]
If I modify an image using the file edit dialog itself, that works as it should.

**Comment by urapadmin** [comment]
@lbestock: I add you here because it might happen to you, too.
There is a trap I step into alllll the time when testing the modification dates: There is a difference between modifying the image itself and adding it to dayplans or what have you. In FM you can't see the modification time of the image itself anywhere, you always only see the modification time of the record that connects the image with the archaeology. Only if you switch test mode on and go to the gallery and, I think, click on the popup button for the image you get to see the modification time of the image record itself. And that would equal what the file edit dialog shows you. It is really confusing but it is correct and strangely without alternative.

The context-specific image description belongs to the record that connects the image and the archaeology. So that would support my assumption that you found yourself in the same 

Could that be the issue? Otherwise I will look into it more deeply. 

BTW: The director's view is the only module that I have not touched. So there you would encounter UTC versions of all the modified fields. For now you can ignore that, there is a ticket: #2883

**Comment by luizaogs** [comment]
I changed the description in FM, so yes. 

But I changed the context-independent description of an image in the file edit dialog itself and THAT got the correct modification date and timezone. Is that not weird? Why does this case get a modification date/time then?

**Comment by urapadmin** [comment]
I might misunderstand but that sounds okay to me:
The context-independent description belongs to the image itself. So when you changed that in the file edit dialog the "modified" field of that image changed.  That description is pretty hard to even see in anywhere FM except in the gallery.
The description in the dayplan or locus_photo belongs to the locus / dayplan and not to the image proper. So when you change those, the modification records of dayplan / locus_photo change but not that of the image.

There are only two ways to manipulate an image's modification timestamp in FM: Either add a new image (not from the gallery) OR go to the gallery on the main page and change the context-independent description in the popup dialog or the image tags. That should have the same effect as changing information in the file edit dialog.

Why is this so complicated? Because one needs both. The context-independent description mostly for Candids and everything that isn't bound to a context. When an image gets bound to a context the binding needs its own description because if the image gets bound to several contexts the description can vary from context to context.

**Comment by luizaogs** [comment]
Then this is fine, I guess.
