### ISSUE TITLE
recording: uncertain period missing in small finds

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2898]
I just realized that in PVD I was only looking for the uncertain period thing in CM, not in the small finds tab. Now in MKAP we seem to only have the period field for small finds (not entirely clear to me why...) and there clicking on a period does not bring up the "uncertain dating" checkbox. Can we add that to the period field for small finds?

**Comment by urapadmin** [comment]
ach, shoot. I forgot that we have two period controls. I think there must be a setting under visibility that controls whether or not you have period under collected material proper.

**Comment by luizaogs** [comment]
Presumably @lbestock and Didi discussed it during configuration last season? I have no idea why we are not using it.

**Comment by urapadmin** [comment]
Hmpf. And they are **separate** period fields in the database. So we have two entirely separate ones and a project could choose to have both of them. So I have to do the same thing again. The forgetting things that my brain does at this age is a curse.

**Comment by urapadmin** [comment]
- visibility/show_period_small_find controls the period in small finds
- visibility/show_period_cm controls period in the "basics" tab

BUT: period in collected materials proper currently would NEVER shows up for small finds. That strikes me wrong for projects that have show_period_small_find set to nope. So I'll change that.

**Comment by urapadmin** [comment]
### recording app 16.2.2 / Kiosk 1.6.2.4 (without time zones) / Kiosk 1.6.5.3 (with time zones)

This is pretty baroque:
- if visibility/show_period_small_find is "yup" 
  - there should be a period and the uncertain date checkbox in the special finds tab
  - if **at the same time** visibility/show_period_cm is "yup" there should be NO period in collected material if a cm is a special find
  - if **at the same time** visibility/show_period_cm is "yup" there should be a period in collected material if a cm is NOT a special find
- if visibility/show_period_cm "yup" you'd have a period field in collected material BUT 
  - if visibility/show_period_small_find is "nope" it would not show up for small finds because that setting says that small_finds don't have periods. 

The latter is the most nonsensical without a use case in reality: No archaeological project will want periods on collected materials UNLESS they are a small find. Rather the other way around: Only small finds have periods (which is possible with these settings and presumably what MKAP is using). It is just really baroque. But for legacy reasons I won't clean it up any further right now. 

- small finds period has a "uncertain dating" checkbox now. But synchronization needs to be checked with that one because it is a separate field and I don't want the two uncertain dates to interfere (would be easy for me to make a mistake and have them confused on the layout or in synchronization)

**Comment by urapadmin** [comment]
the flaw will be tackled in #2893 but not for this MKAP season

**Comment by luizaogs** [comment]
The dating certain field still appears for both CM and small finds.
