### ISSUE TITLE
BUAP: Create loci out of relations

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2908]
Interesting that nobody ever requested this feature before. It would be helpful to create a locus when needed as the opposite of a relation.

I still have a bunch of concerns about this:
- the locus needs a number. Often these numbers are assigned in the order the loci are dug. This would break that pattern
- creating a locus ALWAYS needs to go through the identification method unless in temporary free input mode. Temporary free input is really only for fixing stuff as it and we must never forget about that can break the separation of groups that work parallel. So two users can add a locus with the exact same locus id in temporary free input mode! So we need to go through the identification method. 
- identification methods can be as simple as URAP but potentially also more complex, hinging on the material or some other locus information. I don't think we do that anywhere, currently, but it could be a future request. We just need to keep that in mind. However, creating a new locus as the other side of a relation will go through the same mechanisms as creating it by pressing the + button!

- the original idea for this was to create loci in advance in bulk and that's why this is related to #2903 . But  I am not sure that's wise and the best approach.

**Comment by lbestock** [comment]
The "in the order dug" issue is not a problem. It is generally but not universally true. For instance I will go on a locus assigning spree for architecture that has nothing to do with the order of digging. And because things can always be sorted by "opened on" date, which is a field separate from the creation of the identifier, I anticipate no problem.

As to the structure of the number, yes! It should go through the same mechanisms and result in the same kind of number as other loci, subject to the same rules that apply for creating locus numbers elsewise!

Will be a very helpful addition.

**Comment by urapadmin** [comment]
@liviah848 @maychu16 
guys, question to you: Would it help your workflow if you were able to create a locus in advance? Meaning you would be in the locus relations and when you find out that the locus you try to relate to isn't there already the layout would give you the opportunity to create it without leaving the relations. Would that help with your current work?

**Comment by urapadmin** [comment]
### recording app 16.3
- this is implemented but I call it "experimental". The sequence of actions is pretty complex and I wonder how the iPad deals with it
- remember that adding a locus here must be influenced by the temporary free input the same way as any other button that adds a locus

**Comment by luizaogs** [comment]
Working well, as far as I can tell, including with free input.

**Comment by maychu16** [comment]
Sorry, I totally missed the first email I got from github about this. I think this will be quite useful since so far I have just been working my way around it and adding loci relationships afterwards. I will test this out next week when I input data again.

**Comment by lbestock** [comment]
Wow I just used this for the first time while inputting some 2008 data. I was mostly inputting data as a test of the latest roll out, but this is the first time I have used this feature and I can say that in a real use case with the unstructured narrative data style of early BUAP this is SO HELPFUL. The new locus selection instead of a dropdown has also been extremely helpful. The unstructured data mean a lot of jumping around and these two changes together make it much easier not to miss things.

**Comment by maychu16** [comment]
I really like the new interface. Both in inputting the Locus number and allowing me to select the existing locus.  I no longer have to worry about coming back to the stratigraphic relationship box later. 
I am wondering why we have the Locus number in order in this stratigraphic relationship selection panel but we don't have it in order in the main Loci panel.

**Comment by maychu16** [comment]
Never mind about my comment about loci not being in order in the main view. I just noticed that the interface has been improved and I can sort by Locus or Locus type now. This is really helpful!
