### ISSUE TITLE
configuration: su ceramics language configuration key does not synchronize

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2933]
Testing RuBab. @urapadmin had set it to en for the language, but in testing it was it. I tried it - changed the configuration to en, saw that it was working properly, uploaded and synchronized. Downloaded file is back to Italian.

**Comment by urapadmin** [comment]
actually, that isn't even wrong. The problem is that we never took internationalization to its next stage. The language should be user-dependent and hence synchronizing for the whole project would not make sense. But we never really finished this. 
So for now I'll make it synchronize but in the end that's making it wrong.

**Comment by luizaogs** [comment]
Is this only done for rubab itself?

**Comment by urapadmin** [comment]
### recording app 16.4.3
- no, all projects will get patched so that this synchronizes.

**Comment by luizaogs** [comment]
Synchronizes. Do you need a separate ticket for the internationalization per user thing?

**Comment by urapadmin** [comment]
no, we're not developing this any further
