### ISSUE TITLE
Preserved Height box bug?

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2948]
The excavator's note has texts for the preserved height. When I typed them in, I noticed that the recording app turned them into numbers only. But I can see the notes I typed in if I clicked the box. Not sure if it is a bug or if I am not supposed to type texts in there.

<img width="1008" alt="Screenshot 2024-10-31 at 11 54 42 PM" src="https://github.com/user-attachments/assets/2d11beff-c9e4-4871-b272-f02bcdc05277">
<img width="1512" alt="Screenshot 2024-10-31 at 11 54 34 PM" src="https://github.com/user-attachments/assets/2c1a9494-5469-4abe-8dfb-836a3fc4ef90">

**Comment by urapadmin** [comment]
### recording 16.2.5, rolled out to BUAP on 1.XI.24 11:00 pm 
I copy @liviah848 here to spread the information. (I guess I should make a BUAP group)

it was the same with wall thickness: FileMaker allows inputting text in numerical fields by default. Drives me nuts. And then Kiosk would eradicate everything that isn't a number. 
- I have limited both fields explicitly to mere numerical inputs in FileMaker. 
- brick size and stone size have been and keep being text fields because they are famous for having all kinds of inputs

The question that remains is where to put the narrative: Please discuss it with @lbestock I also wonder if the fields we have here should be extended or refined. E.g. nobody would have a clue about what units of measurements to use here.

**Comment by luizaogs** [comment]
This is working as you outline above. Since it still seems to require discussion, I won’t close it but I will remove it from testing.

**Comment by urapadmin** [comment]
@lbestock Another reminder that that might need your attention.
For me it is done and so I close this

**Comment by luizaogs** [comment]
For what it’s worth Lutz, and since you still have room in the layout, a “further observations on measurements” text field (similar to what we did for CM) or something could be useful. I only chime in because it is something that could have been useful for MADP too but I think we just ended up adding notes to the general locus observations since they didn’t fit here.

**Comment by urapadmin** [comment]
which was the right place to put it right now, I think.
The downside of too many description fields in several places might be that information gets a bit scattered and it gets harder to get the whole picture. But I thought a free input in the architecture layout cannot hurt.
However, I before I extend the architecture layout I want to hear what BUAP and Abydos actually need. There might be more ...

**Comment by urapadmin** [comment]
- actually let's have that discussion somewhere else: #2960
