### ISSUE TITLE
recording app: lists in relations are not sorted properly for BUAP

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2953]
BUAP first meeting with Abydos team! We are inputting relations.
We note that the list of loci for defining the relation is not sorted, and sometimes there are a ton of loci and it gets confusing. Can this list please sort better?
![image](https://github.com/user-attachments/assets/b7d4bcac-1a2c-49f4-9985-f3314dd2fb64)

**Comment by lbestock** [comment]
@liviah848 adding you. (Though you are working on a thesis chapter right now!)
Aha at least I understand the sorting mostly better now: the single digits are treated like 40, not like 04. So it's not random, though it would still be better if it sorted as though it were 04. 

Also what on earth is 184-5 doing up there in 183??

**Comment by urapadmin** [comment]
(my notes)
- reminds me of #2230
If those lists get too long they become rather useless. I'd rather go with something more intelligent that allows a filter or so. 
Why not use what we have:
![grafik](https://github.com/user-attachments/assets/636371f9-47d8-460c-ad7a-628f7e0e1ab5)
If I set the current OP as default OP filter you'd get a list of the loci. And here I have more options to apply a different sorting method. 
We do have a config key that allows configuring the sort order in registration: registration_identifier_sort_method. I suppose that solves the same problem in a different part of the UI.

**Comment by urapadmin** [comment]
> 184-5 doing up there in 183

![grafik](https://github.com/user-attachments/assets/fb6f4f5d-5fa7-4272-941b-904e827aa9cf)

I guess that needs some temporary free input :o)

**Comment by lbestock** [comment]
Oh right! Not automatic numbering and you get the same kinds of mistakes you get with paper in the first place :) I wonder whether that was on the sheet or a data entry error.

**Comment by lbestock** [comment]
I've temporarily free input to fix the misnumbered locus. But back to the actual point of this ticket, I think you're right that solving the sort-order is perhaps less helpful than having a search.

Where else is this going to be useful? Where does one have to pick something from a list, where it becomes problematic when that list is too long? In Abydos it is going to be a problem on the homepage for OP selection - there are over 200. In the locus list within an OP, as USTP already encountered. In locus relations.

**Comment by urapadmin** [comment]
> I've temporarily free input to fix the misnumbered locus. But back to the actual point of this ticket, I think you're right that solving the sort-order is perhaps less helpful than having a search.
> 
> Where else is this going to be useful? Where does one have to pick something from a list, where it becomes problematic when that list is too long? In Abydos it is going to be a problem on the homepage for OP selection - there are over 200. In the locus list within an OP, as USTP already encountered. In locus relations.

The search button would solve your problem there

**Comment by urapadmin** [comment]
So these are the tasks here:
- [x] in locus relations use the current unit as the default when opening the locus selection popup. There is a very nuanced config key: locus_selector_current_unit_defaults can be set to "nope" and then the current unit will not be set as the default filter (this is the better setting if you only want to use the locus selector when you refer to a locus of a different unit)
- [x] locus_identifier_sort_method: can be either domain (the default) or nothing (I mean an empty field), which is alphanumeric and that's what we have currently.

**Comment by urapadmin** [comment]
while that works for field projects that create their numbers automatically, id does not work for BUAP, which uses plain free input.
184-5 looks to us like two separate numbers but it is actually one text. So it is sorted alphanumerically and "183-10" comes before "183-5".  All I could do is something super hacky and invent a sorting method that splits the text into two portions and sort by them individually. 

But that would be such a BUAP-only addition that I hesitate.

**Comment by urapadmin** [comment]
### recording app 16.3

- [x] in locus relations the current unit is used as the default when opening the locus selection popup unless the config key "visibility/locus_selector_current_unit_defaults" is set to "nope"(which is the better setting if you only want to use the locus selector when you refer to a locus of a different unit). The default stays "nope" (that has been the behaviour ever since)
- [x] general/locus_identifier_sort_method can be either domain or nothing (I mean an empty field), which is alphanumeric and that's what we have had so far. The default here will be "domain". So this changes for all current projects.  
The relevant lists here are the locus list in excavation and the locus selection popup. Other lists stay the same for now.

- For BUAP this has no effect until we convert all current inputs to match the domain/serial number pattern. That needs some thinking and happens in a different ticket: #2956 

⚠️ Just as a warning: If you test this in PVD you might get problematic results because the PVD data is a mess at this point. We have changed identification methods back and forth and thus created a mix of numbering strategies within the same unit that cannot be remedied with any sorting strategy. You'd have to use a unit that has been consistently populated with the same identification method.

**Comment by urapadmin** [comment]
@lbestock 
> Aha at least I understand the sorting mostly better now: the single digits are treated like 40, not like 04. So it's not random, though it would still be better if it sorted as though it were 04.

No, that is not really the explanation. The identifier is sorted alphanumerical. It compares digits at the same position with one another and decides: 
10
4
compares 1 and 4 with the result that 4 is greater than 1. The result is:
10
4

If the first digits are equal it compares the next position:
41
401
4 is equal, so the comparison between 1 and 0 decides. 1 is greater than 0 -> 41 wins and the result would be
401
41

It is easier to understand why this is necessary if you look at other identifiers like
SU2345-12345 or something like that. The app simply does not know (because it is abstract and works for all projects) that these are two numbers and not one long text.

**Comment by luizaogs** [comment]
Hmm Lutz I’m not sure the domain vs empty field is making a difference? At least I’m testing with PBA which has used the same numbering strategy for all loci and I created a bunch more to get into numbers that could be problematic, based on the BUAP trouble above. I have both PBA-001 and PBA-010, for instance, and that is being sorted the same (correct) way with both values in configuration. 

Also, when I downloaded the dock there was an empty field rather than domain in there. Since you say you want domain to be the default I let you know.

This is the sorting in both cases: 

![Image](https://github.com/user-attachments/assets/77d7e325-9102-4ed5-a241-225d7d6082f3)

**Comment by urapadmin** [comment]
ja, in this case it wouldn't make a difference. As long as the numbers have leading zeroes alphanumeric sorting comes out the same as numeric sorting. The issue appears in BUAP because the serial locus number does not have leading zeroes. Would be PBA-1, PBA-2 etc. 
I realize now that to test this we would have to change the PVD identification methods.

**Comment by urapadmin** [comment]
sorry, I was blind at first and not clear enough in my roll out message: THAT list (and its kind) hasn't changed at all (perhaps I find a way to do that later, but it is much harder to make that configurable). 
With a large number of loci it gets unwieldy anyhow (like in #2230) and so I ignored that for now in favour of the selection popup.

The relevant lists here are the locus list in excavation and the list of loci when you click on the list button in locus relations and chose select. I add that.

**Comment by luizaogs** [comment]
Ok, the sorting was the same in all of those. Do you want to change the identifier method in PVD for me to test it there?

**Comment by urapadmin** [comment]
I am on it right now. And it doesn't look so good :-/

**Comment by urapadmin** [comment]
- "domain" is NOT the default currently but was supposed to.
- sorting by "date opened" without any date opened timestamps should use "created" instead. It doesn't. It doesn't do anything.
  - Oh, not true. It works with "domain" as the method but not without it (while that should not make a difference at all for sorting by date)
- the identifier is sorted in ascending order. That's not what we are used to.
- but at least the sorting obeys the "domain" value correctly.
- in the list in the locus selector the "domain" setting does not make a difference. The sorting order is always numerical. How can that be?

**Comment by urapadmin** [comment]
### recording 16.3.1
- [x] sorting by "date opened" without any "date opened" timestamps should use "created" instead. It should work now with "domain" as the method or without it.
- [x] kept the ascending order of the identifier. Apparently that was what we had
- [x] the difference between "domain" and not domain should show in the locus selector as well
- [x] as for the drop down lists: I have looked into it and there is no reasonable way to have those sorted anything but alphanumerically. So nothing I can do for these lists. So instead I have eliminated the locus drop down list in the header (see also #2230) and switched to the locus selector. In this case the unit cannot be changed, though. The selection must be limited to the loci of the current unit.

**Comment by urapadmin** [comment]
> Ok, the sorting was the same in all of those. Do you want to change the identifier method in PVD for me to test it there?

- yes, please. And it goes particularly well with #2956
