### ISSUE TITLE
recording: do we need a locus drop-down in relations?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2962]
A question/perhaps a suggestion. Now that the locus selector exists in relations, does it not make sense to get rid of the locus dropdown there? I can see having both options being a bit confusing. And not having the dropdown gets rid of potential ordering problems. I guess if this were done it would just make sense to always have the selector able to go to different units too, rather than having that config key that allows you to limit it to the current unit. 

Just a thought that occurred to me.

**Comment by urapadmin** [comment]
ja, that's why I am not so sure. Back then in my hay days we all wanted options to absolutely refine our workflow. In the 21st century options seem to overwhelm and confuse users rather than help. Just my slightly sociological 10 cents here. It explains why I thought I should invent 500 config keys.
However, the drop down is still the fastest way to select a locus (one click) and for many projects it has been fine. Even the alphanumerical sorting is only an issue for projects that use a serial number without leading zeroes. 
So I was reluctant to give it up here. But maybe you are right. I am not the intended user here. 

I think I'll invent a config key that leaves a project the option of that option :o)

**Comment by urapadmin** [comment]
### recording app 16.4
- "show_locus_relation_dropdown" does exactly that. The default is "nope", so no dropdown anymore unless somebody asks for it.

**Comment by luizaogs** [comment]
This is working and I think it's better. But one comment: should the locus selector open with the current unit as the default, and then users can simply change it if they need another unit? That would mitigate your worry about the dropdown being easier to use for projects that just need relations in the same unit.

**Comment by urapadmin** [comment]
well, that is what the setting "locus_selector_current_unit_defaults" does. I guess it is better to set it to "yup" by default if we hide the locus selector by default as well. In the end you are right, deleting the default value in case of a cross-unit relation is much quicker than having to type the current unit over and over again if one just wants to relate to a locus within the same unit.

so I make "locus_selector_current_unit_defaults" the default value for the future. I close this here, nonetheless.
