### ISSUE TITLE
BUAP recording app: formatting funniness in narrative images after latest update

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2971]
Slight wonkiness in the images layout at unit level after the latest rollout.
![image](https://github.com/user-attachments/assets/5ece6d5b-3ed7-4b0d-b8f8-c1b13d0226e2)

There's an errant "don't show this again" (which can be clicked away). While it's there, there is a bit of a green thing behind the top images if that helps you find it?

**Comment by urapadmin** [comment]
That's the narrative hint that appears after you set the cursor in a narrative field. I am not sure why it got moved to the background.
But it also only appears if the configuration key help_daily_narrative has a text AND suppress_hint_daily_narrative is "nope".
Please check those settings in BUAP.

**Comment by urapadmin** [comment]
### recording app 16.4.5
- the hint is now back in the foreground. As a reminder: It goes away if one just clicks into it (it reappears with every narrative until one finally uses "don't show again")

**Comment by luizaogs** [comment]
The hint is back in the foreground and working as it should, but BUAP has a "yup" for the suppress daily narrative hint so seems like that configuration key is not working.

**Comment by urapadmin** [comment]
I downloaded your dock and tried it and can't reproduce this. 
If I set "suppress_hint_daily_narrative" to nope the hint shows, if I set it to "yup" (which is the same as using the "don't show this again" button on the hint, the narrative does not show up again. So that looks okay to me. 

One thing I forgot to mention here is that the config key "suppress_hint_daily_narrative" does not sync. It is always set to "nope" after a dock download. If a project wants to get rid of the message for good it needs to delete the text of the hint.

**Comment by urapadmin** [comment]
I can also not confirm tat BUAP has a "yup" to begin with. When downloading your dock I see a "nope" as the initial value.

**Comment by luizaogs** [comment]
I did not change the configuration key. What I did was click the "don't show it again" button. Then when I looked at configuration the yup was there. If that's how it's supposed to work, then that's fine.

**Comment by urapadmin** [comment]
> I did not change the configuration key. What I did was click the "don't show it again" button. Then when I looked at configuration the yup was there. If that's how it's supposed to work, then that's fine.

yes, that is how it works.
