### ISSUE TITLE
kiosk/recording app: image sorting

### ISSUE THREAD

**Issue by efinn27** [arch-kiosk/arch-kiosk-office#2992]
Hi! This is more of a question but when inputting images into a Locus, the images end up adding to the front of the list (so the first image you add out of say 3 images become 3/3 and the last ones become 1/3). Is there a reason this was done? I don't think it would normally be a problem, but when we are adding in context sheets it get a little weird because the front of the sheet tends to appear after the back.

**Comment by urapadmin** [comment]
the numbering is not bound to the image but to the position in the list. The number tells you where in the list you are and how many more are down or up. Because the most recently added photo is always sorted to the top it it is also always #1/whatever. 
the numbering is not reflecting the order in which images have been put in.

The only way to make it more natural to the process of inputting legacy data would be to change the sort order from oldest on top to most recent on the bottom. 

But perhaps knowing about the semantics of that number is already sufficient to not have it trip you up.
