### ISSUE TITLE
recording app: make new OP from archival entity

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#3015]
It really would be helpful to be able to create OPs in the OP link section, same way we can create loci in the relations. I am usually creating a record for stuff that has not been put in yet. So the OPs usually don’t exist. I have to exit, create the OPs, then go back and link them. This is a step I find I often skip because it is cumbersome, but that’s some of the most important information.

**Comment by urapadmin** [comment]
That's not possible simply because a unit needs a lot of information before it can be created. That's why the layout for adding a unit is so big and complicated. I can send you to that layout, but I don't think that's exactly what would help you, would it?

**Comment by lbestock** [comment]
It would be at least a little easier. No, I see what you mean. I end up not putting in all the information for the unit, because I don’t know it at the time I am creating it. I mean the absolute dream is totally impossible, it is that I just write the OP numbers, and then when those OPs end up being created later the link would just appear there. Sort of like the ANC data gets imported with seeming magic once the relevant locus and lot are created. But I say it just so you can see what it is that would help, not because I think it’s a reasonable request.

**Comment by urapadmin** [comment]
Ja, that would be so extremely tailored to your just-now use case that I must refuse.

I am not entirely sure what the point of the units list is anyways. Jumping there? 
You could simply type the OP into the description. If we equip it with a button for reference navigation you can even jump to those units. I was close to throw the whole unit thing out because I had a hunch it wasn't all that useful (and is at least already a pretty bespoke BUAP/ANC feature that others would not need). So we could turn that list even into another text field in which one can list all kinds of identifiers.

**Comment by lbestock** [comment]
Oh yes. Navigation. Then we could just do away with that tab, even. I have been just naturally putting the OPs in the description anyway. Navigation there would be perfect.

**Comment by urapadmin** [comment]
### recording app 16.7.2
- there is a new config key under visibility: "show_archive_unit_links". Default is "yup" but if you set it to "nope" the unit links in the archive layout disappear.
- the description field has reference navigation now
