### ISSUE TITLE
dayplan/narrative link between dayplans and narratives requested

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#89]
dayplan/narrative link between dayplans and narratives (possibly covered by daily  director review in hte browser - do we need it in the recording system  itself?)
-- | --

**Comment by urapadmin** [comment]
a way to visualize the connection has been tried for arch1900. Needs Feedback from a project with real data.

**Comment by lbestock** [comment]
I want Sam testing this one in USTP using real context sheets and real photos.

**Comment by SamKimball-BrownU** [comment]
I need the data in order to test this one

**Comment by SamKimball-BrownU** [comment]
I don't really know what we can do with this ticket nowadays, except I will reference #739 

Perhaps close it once we get further into the season and @lbestock sees how useful it is for interpreting narratives

**Comment by urapadmin** [comment]
I move it to the future.

**Comment by urapadmin** [comment]
Laurel, where are we with this one?

**Comment by lbestock** [comment]
I have not found it useful in the PVD season because I never understood it properly. I did not find it useful in director's view in URAP but I have not yet put PVD through the director's view test and we know in some ways that is a better test. I need to internalize what it is supposed to do and how before trying that.

**Comment by urapadmin** [comment]
closed in favor of #1823
